/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tercero;

import java.awt.Dimension;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JOptionPane;

/**
 *
 * @author CAT
 */
public class metodo_Secante extends javax.swing.JFrame {

    /**
     * Creates new form metodo_Secante
     */
    public metodo_Secante() {
        initComponents();
        this.setTitle("Metodo de la Secante");
        this.setMinimumSize(new Dimension(816, 399));
        this.setMaximumSize(new Dimension(816, 399));
        jTx6.setEnabled(false);
        jTx5.setEnabled(false);
        jTx4.setEnabled(false);
        jTx3.setEnabled(false);
        jTx2.setEnabled(false);
        jTx.setEnabled(false);
        jTc.setEnabled(false);
        jTrelativeerror.setEnabled(false);
        jTiteracion.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTc = new javax.swing.JTextField();
        jRc = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTx6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jR6 = new javax.swing.JRadioButton();
        jTx5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTx1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTx3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTx2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTx = new javax.swing.JTextField();
        jR5 = new javax.swing.JRadioButton();
        jR4 = new javax.swing.JRadioButton();
        jR3 = new javax.swing.JRadioButton();
        jR2 = new javax.swing.JRadioButton();
        jR1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jTx4 = new javax.swing.JTextField();
        jTndecimales = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTx0 = new javax.swing.JTextField();
        jTerror = new javax.swing.JTextField();
        jBrun = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTiteracion = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTrelativeerror = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jBclear = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel1.setText("X");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(640, 180, 120, 24);

        jTc.setText("0");
        jPanel1.add(jTc);
        jTc.setBounds(430, 70, 50, 30);

        jRc.setText("c");
        jRc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRcActionPerformed(evt);
            }
        });
        jPanel1.add(jRc);
        jRc.setBounds(430, 40, 50, 23);

        jLabel2.setFont(new java.awt.Font("Dubai Light", 0, 12)); // NOI18N
        jLabel2.setText("X");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(410, 70, 7, 30);

        jTx6.setText("0");
        jPanel1.add(jTx6);
        jTx6.setBounds(10, 70, 50, 30);

        jLabel3.setFont(new java.awt.Font("Dubai Light", 0, 12)); // NOI18N
        jLabel3.setText("X^6");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 70, 19, 30);

        jR6.setText("x^6");
        jR6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR6ActionPerformed(evt);
            }
        });
        jPanel1.add(jR6);
        jR6.setBounds(10, 40, 50, 23);

        jTx5.setText("0");
        jPanel1.add(jTx5);
        jTx5.setBounds(80, 70, 50, 30);

        jLabel4.setFont(new java.awt.Font("Dubai Light", 0, 12)); // NOI18N
        jLabel4.setText("X^5");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 70, 19, 30);

        jTx1.setText("0");
        jTx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTx1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTx1);
        jTx1.setBounds(230, 140, 50, 30);

        jLabel5.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel5.setText(",");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(220, 150, 10, 20);

        jTx3.setText("0");
        jPanel1.add(jTx3);
        jTx3.setBounds(220, 70, 50, 30);

        jLabel6.setFont(new java.awt.Font("Dubai Light", 0, 12)); // NOI18N
        jLabel6.setText("X^3");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(270, 70, 19, 30);

        jTx2.setText("0");
        jPanel1.add(jTx2);
        jTx2.setBounds(290, 70, 50, 30);

        jLabel7.setFont(new java.awt.Font("Dubai Light", 0, 12)); // NOI18N
        jLabel7.setText("X^2");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(340, 70, 19, 30);

        jTx.setText("0");
        jPanel1.add(jTx);
        jTx.setBounds(360, 70, 50, 30);

        jR5.setText("x^5");
        jR5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR5ActionPerformed(evt);
            }
        });
        jPanel1.add(jR5);
        jR5.setBounds(80, 40, 50, 23);

        jR4.setText("x^4");
        jR4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR4ActionPerformed(evt);
            }
        });
        jPanel1.add(jR4);
        jR4.setBounds(150, 40, 50, 23);

        jR3.setText("x^3");
        jR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR3ActionPerformed(evt);
            }
        });
        jPanel1.add(jR3);
        jR3.setBounds(220, 40, 50, 23);

        jR2.setText("x^2");
        jR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR2ActionPerformed(evt);
            }
        });
        jPanel1.add(jR2);
        jR2.setBounds(290, 40, 50, 23);

        jR1.setText("x");
        jR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR1ActionPerformed(evt);
            }
        });
        jPanel1.add(jR1);
        jR1.setBounds(360, 40, 50, 23);

        jLabel8.setFont(new java.awt.Font("Dubai Light", 1, 13)); // NOI18N
        jLabel8.setText("N° Decimals:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(300, 190, 80, 23);

        jTx4.setText("0");
        jTx4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTx4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTx4);
        jTx4.setBounds(150, 70, 50, 30);

        jTndecimales.setText("0");
        jTndecimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTndecimalesActionPerformed(evt);
            }
        });
        jPanel1.add(jTndecimales);
        jTndecimales.setBounds(300, 220, 130, 30);

        jLabel9.setFont(new java.awt.Font("Dubai Light", 0, 12)); // NOI18N
        jLabel9.setText("X^4");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(200, 70, 19, 30);

        jLabel10.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel10.setText("[");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(160, 140, 10, 30);

        jLabel11.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel11.setText("]");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(280, 140, 10, 30);

        jLabel12.setFont(new java.awt.Font("Dubai Light", 1, 13)); // NOI18N
        jLabel12.setText("Interval:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 110, 80, 23);

        jLabel13.setFont(new java.awt.Font("Dubai Light", 1, 13)); // NOI18N
        jLabel13.setText("Error:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 190, 80, 23);

        jTx0.setText("0");
        jTx0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTx0ActionPerformed(evt);
            }
        });
        jPanel1.add(jTx0);
        jTx0.setBounds(170, 140, 50, 30);

        jTerror.setText("0");
        jTerror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTerrorActionPerformed(evt);
            }
        });
        jPanel1.add(jTerror);
        jTerror.setBounds(10, 220, 130, 30);

        jBrun.setText("Run");
        jBrun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrunActionPerformed(evt);
            }
        });
        jPanel1.add(jBrun);
        jBrun.setBounds(10, 310, 130, 30);

        jTiteracion.setColumns(20);
        jTiteracion.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTiteracion.setRows(5);
        jScrollPane3.setViewportView(jTiteracion);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(520, 200, 270, 130);

        jTrelativeerror.setColumns(20);
        jTrelativeerror.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTrelativeerror.setRows(5);
        jScrollPane4.setViewportView(jTrelativeerror);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(520, 40, 270, 130);

        jLabel14.setFont(new java.awt.Font("Dubai Light", 1, 13)); // NOI18N
        jLabel14.setText("Enable function:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 20, 120, 23);

        jLabel15.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel15.setText("Relative Error");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(610, 20, 120, 24);

        jBclear.setText("Reset");
        jBclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBclearActionPerformed(evt);
            }
        });
        jPanel1.add(jBclear);
        jBclear.setBounds(350, 310, 130, 30);

        jLabel16.setBackground(new java.awt.Color(51, 204, 255));
        jLabel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel16);
        jLabel16.setBounds(500, 0, 300, 370);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tercero/cat-1027486_1280.jpg"))); // NOI18N
        jLabel17.setText("jLabel17");
        jLabel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel17);
        jLabel17.setBounds(-410, 0, 910, 420);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTx1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTx1ActionPerformed

    private void jTx4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTx4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTx4ActionPerformed

    private void jTndecimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTndecimalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTndecimalesActionPerformed

    private void jTx0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTx0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTx0ActionPerformed

    private void jTerrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTerrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTerrorActionPerformed

    private void jBrunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrunActionPerformed
        double x6 = 0, x5 = 0, x4 = 0, x3 = 0, x2 = 0, x = 0, x1 = 0, x0 = 0, c = 0, error = 0, fx0 = 0, fx1 = 0, xi = 0, errorrelativo = 0, newx1 = 0, newx0 = 0, newxi = 0;
        int ndecimales = 0, conta;
        if (jTx6.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de la X^6", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                x6 = Double.parseDouble(jTx6.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio de la X^6", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }////////////////////////////////////
        if (jTx5.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de la X^5", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                x5 = Double.parseDouble(jTx5.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio de la X^5", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }//////////////////////////////////
        if (jTx4.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de la X^4", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                x4 = Double.parseDouble(jTx4.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio de la X^4", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }//////////////////////////////////
        if (jTx3.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de la X^3", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                x3 = Double.parseDouble(jTx3.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio de la X^3", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }//////////////////////////////////
        if (jTx2.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de la X^2", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                x2 = Double.parseDouble(jTx2.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio de la X^2", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }//////////////////////////////////
        if (jTx.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de la X", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                x = Double.parseDouble(jTx.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio de la X", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }//////////////////////////////////
        if (jTc.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de la Constante", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                c = Double.parseDouble(jTc.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio de la Constante", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }//////////////////////////////////
        if (jTerror.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio del error", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                error = Double.parseDouble(jTerror.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio del error", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }//////////////////////////////////
        if (jTndecimales.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de los decimales", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                ndecimales = Integer.parseInt(jTndecimales.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio de los decimales", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }//////////////////////////////////
        if (jTx1.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de x1", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                x1 = Integer.parseInt(jTx1.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio de x1", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }//////////////////////////////////
        if (jTx0.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de x0", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                x0 = Integer.parseInt(jTx0.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio de x0", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }//////////////////////////////////
        if (jR1.isSelected() == true || jR2.isSelected() == true || jR3.isSelected() == true || jR4.isSelected() == true || jR5.isSelected() == true || jR6.isSelected() == true || jRc.isSelected() == true) {
            if (x0 > x1) {
                JOptionPane.showMessageDialog(null, "El intervalo x0 debe de ser menor a x1", "Error intervalo", JOptionPane.INFORMATION_MESSAGE);
            } else {

                conta = 1;
                fx0 = ((x6 * Math.pow(x0, 6)) + (x5 * Math.pow(x0, 5)) + (x4 * Math.pow(x0, 4)) + (x3 * Math.pow(x0, 3)) + (x2 * Math.pow(x0, 2)) + (x * Math.pow(x0, 1) + (c)));
                fx1 = ((x6 * Math.pow(x1, 6)) + (x5 * Math.pow(x1, 5)) + (x4 * Math.pow(x1, 4)) + (x3 * Math.pow(x1, 3)) + (x2 * Math.pow(x1, 2)) + (x * Math.pow(x1, 1) + (c)));
                xi = (x1 - (fx1 * (x0 - x1)) / (fx0 - fx1));
                System.out.println(conta);
                do {      
                System.out.println("newxi "+newxi);
                    System.out.println("xi "+xi);
                    newx0 = x1;//x1 le va a pasar el valor a la nueva x0
                    x0 = newx0;//donde x0 sera igual a la nueva x0
                    newx1 = xi;//nueva x1 sera igual a lo que dio de resultado xi
                    x1 = newx1;//donde se le pasara el valor a x1
                    fx0 = ((x6 * Math.pow(x0, 6)) + (x5 * Math.pow(x0, 5)) + (x4 * Math.pow(x0, 4)) + (x3 * Math.pow(x0, 3)) + (x2 * Math.pow(x0, 2)) + (x * Math.pow(x0, 1) + (c)));
                    fx1 = ((x6 * Math.pow(x1, 6)) + (x5 * Math.pow(x1, 5)) + (x4 * Math.pow(x1, 4)) + (x3 * Math.pow(x1, 3)) + (x2 * Math.pow(x1, 2)) + (x * Math.pow(x1, 1) + (c)));
                    newxi=xi;//se le pasa el valor de la xi a una nueva xi para poder hacer el error
                    xi = (x1 - (fx1 * (x0 - x1)) / (fx0 - fx1));          
                    errorrelativo = Math.abs((xi - newxi) / xi) * 100;
                    BigDecimal equis=new BigDecimal(xi);
                    equis=equis.setScale(ndecimales, RoundingMode.HALF_UP);
                    BigDecimal elerror=new BigDecimal(errorrelativo);
                    elerror=elerror.setScale(ndecimales, RoundingMode.HALF_UP);
                    jTiteracion.append("X"+conta+"\t\t"+equis+"\n");
                    jTrelativeerror.append("X"+conta+"\t\t"+elerror+"\n");                  
                    conta++;
                } while (errorrelativo >= error || conta >= 100);
            }
        }


    }//GEN-LAST:event_jBrunActionPerformed

    private void jR6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR6ActionPerformed
        if (jR6.isSelected() == false) {
            jTx6.setEnabled(false);
        } else {
            jTx6.setEnabled(true);
        }
    }//GEN-LAST:event_jR6ActionPerformed

    private void jR5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR5ActionPerformed
        if (jR5.isSelected() == false) {
            jTx5.setEnabled(false);
        } else {
            jTx5.setEnabled(true);
        }
    }//GEN-LAST:event_jR5ActionPerformed

    private void jR4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR4ActionPerformed
        if (jR4.isSelected() == false) {
            jTx4.setEnabled(false);
        } else {
            jTx4.setEnabled(true);
        }
    }//GEN-LAST:event_jR4ActionPerformed

    private void jR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR3ActionPerformed
        if (jR3.isSelected() == false) {
            jTx3.setEnabled(false);
        } else {
            jTx3.setEnabled(true);
        }
    }//GEN-LAST:event_jR3ActionPerformed

    private void jR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR2ActionPerformed
        if (jR2.isSelected() == false) {
            jTx2.setEnabled(false);
        } else {
            jTx2.setEnabled(true);
        }
    }//GEN-LAST:event_jR2ActionPerformed

    private void jR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR1ActionPerformed
        if (jR1.isSelected() == false) {
            jTx.setEnabled(false);
        } else {
            jTx.setEnabled(true);
        }
    }//GEN-LAST:event_jR1ActionPerformed

    private void jRcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRcActionPerformed
        if (jRc.isSelected() == false) {
            jTc.setEnabled(false);
        } else {
            jTc.setEnabled(true);
        }
    }//GEN-LAST:event_jRcActionPerformed

    private void jBclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBclearActionPerformed
        jTc.setText("0");
        jTx.setText("0");
        jTx2.setText("0");
        jTx3.setText("0");
        jTx4.setText("0");
        jTx5.setText("0");
        jTx6.setText("0");
        jTx0.setText("0");
        jTx1.setText("0");
        jTerror.setText("0");
        jTndecimales.setText("0");
        jTc.setEnabled(false);
        jTx.setEnabled(false);
        jTx2.setEnabled(false);
        jTx3.setEnabled(false);
        jTx4.setEnabled(false);
        jTx5.setEnabled(false);
        jTx6.setEnabled(false);
        jR1.setSelected(false);
        jR2.setSelected(false);
        jR3.setSelected(false);
        jR4.setSelected(false);
        jR5.setSelected(false);
        jRc.setSelected(false);
        jR6.setSelected(false);
        jTiteracion.setText("");
        jTrelativeerror.setText("");
    }//GEN-LAST:event_jBclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(metodo_Secante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(metodo_Secante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(metodo_Secante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(metodo_Secante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                metodo_Secante popo = new metodo_Secante();
                popo.setLocationRelativeTo(null);
                popo.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBclear;
    private javax.swing.JButton jBrun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jR1;
    private javax.swing.JRadioButton jR2;
    private javax.swing.JRadioButton jR3;
    private javax.swing.JRadioButton jR4;
    private javax.swing.JRadioButton jR5;
    private javax.swing.JRadioButton jR6;
    private javax.swing.JRadioButton jRc;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTc;
    private javax.swing.JTextField jTerror;
    private javax.swing.JTextArea jTiteracion;
    private javax.swing.JTextField jTndecimales;
    private javax.swing.JTextArea jTrelativeerror;
    private javax.swing.JTextField jTx;
    private javax.swing.JTextField jTx0;
    private javax.swing.JTextField jTx1;
    private javax.swing.JTextField jTx2;
    private javax.swing.JTextField jTx3;
    private javax.swing.JTextField jTx4;
    private javax.swing.JTextField jTx5;
    private javax.swing.JTextField jTx6;
    // End of variables declaration//GEN-END:variables

}
