/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tercero;

import java.awt.Dimension;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JOptionPane;

/**
 *
 * @author CAT
 */
public class metodo_Newton extends javax.swing.JFrame {

    /**
     * Creates new form metodo_Newton
     */
    public metodo_Newton() {
        initComponents();
        this.setMaximumSize(new Dimension(570, 770));
        this.setMinimumSize(new Dimension(570, 770));
        this.setTitle("Método de Newton Raphson");
        jTer.setEnabled(false);
        jTxxx.setEnabled(false);
        jTc.setEnabled(false);
        jTx.setEnabled(false);
        jTx2.setEnabled(false);
        jTx3.setEnabled(false);
        jTx4.setEnabled(false);
        jTx5.setEnabled(false);
        jTx6.setEnabled(false);
        jTcc.setEnabled(false);
        jTxx.setEnabled(false);
        jTx22.setEnabled(false);
        jTx33.setEnabled(false);
        jTx44.setEnabled(false);
        jTx55.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRc = new javax.swing.JRadioButton();
        jTcc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTndecimales = new javax.swing.JTextField();
        jR6 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTx55 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTx44 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTx33 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTx22 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxx = new javax.swing.JTextField();
        jR5 = new javax.swing.JRadioButton();
        jR4 = new javax.swing.JRadioButton();
        jR3 = new javax.swing.JRadioButton();
        jR2 = new javax.swing.JRadioButton();
        jR1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTx6 = new javax.swing.JTextField();
        jTvalorinicial = new javax.swing.JTextField();
        jTerror = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTer = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxxx = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jBresetear = new javax.swing.JButton();
        jBrun = new javax.swing.JButton();
        jTx5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTx4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTx3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTx2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTx = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTc = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("x");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(470, 150, 10, 30);

        jRc.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jRc.setText("c");
        jRc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRcActionPerformed(evt);
            }
        });
        jPanel1.add(jRc);
        jRc.setBounds(480, 60, 50, 32);

        jTcc.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jTcc.setText("0");
        jTcc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTcc);
        jTcc.setBounds(480, 150, 60, 30);

        jLabel2.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("N° decimals:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(420, 200, 110, 30);

        jTndecimales.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        jTndecimales.setText("0");
        jPanel1.add(jTndecimales);
        jTndecimales.setBounds(400, 230, 130, 30);

        jR6.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jR6.setText("6");
        jR6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR6ActionPerformed(evt);
            }
        });
        jPanel1.add(jR6);
        jR6.setBounds(20, 60, 50, 32);

        jLabel3.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("f'(x)=");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 150, 40, 30);

        jTx55.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jTx55.setText("0");
        jTx55.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTx55);
        jTx55.setBounds(50, 150, 60, 30);

        jLabel4.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("x^5");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 150, 30, 30);

        jTx44.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jTx44.setText("0");
        jTx44.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTx44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTx44ActionPerformed(evt);
            }
        });
        jPanel1.add(jTx44);
        jTx44.setBounds(140, 150, 60, 30);

        jLabel5.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("x^4");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 150, 30, 30);

        jTx33.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jTx33.setText("0");
        jTx33.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTx33);
        jTx33.setBounds(230, 150, 60, 30);

        jLabel6.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("x^3");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(290, 150, 30, 30);

        jTx22.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jTx22.setText("0");
        jTx22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTx22);
        jTx22.setBounds(320, 150, 60, 30);

        jLabel7.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("x^2");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(380, 150, 30, 30);

        jTxx.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jTxx.setText("0");
        jTxx.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTxx);
        jTxx.setBounds(410, 150, 60, 30);

        jR5.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jR5.setText("5");
        jR5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR5ActionPerformed(evt);
            }
        });
        jPanel1.add(jR5);
        jR5.setBounds(100, 60, 50, 32);

        jR4.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jR4.setText("4");
        jR4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR4ActionPerformed(evt);
            }
        });
        jPanel1.add(jR4);
        jR4.setBounds(180, 60, 50, 32);

        jR3.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jR3.setText("3");
        jR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR3ActionPerformed(evt);
            }
        });
        jPanel1.add(jR3);
        jR3.setBounds(260, 60, 50, 32);

        jR2.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jR2.setText("2");
        jR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR2ActionPerformed(evt);
            }
        });
        jPanel1.add(jR2);
        jR2.setBounds(340, 60, 50, 32);

        jR1.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jR1.setText("1");
        jR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR1ActionPerformed(evt);
            }
        });
        jPanel1.add(jR1);
        jR1.setBounds(420, 60, 50, 32);

        jLabel8.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setText("Enable function:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 20, 110, 30);

        jLabel9.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 51));
        jLabel9.setText("Er");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(390, 280, 40, 30);

        jLabel10.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 51));
        jLabel10.setText("Error %:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(240, 200, 110, 30);

        jTx6.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        jTx6.setText("0");
        jPanel1.add(jTx6);
        jTx6.setBounds(20, 90, 50, 30);

        jTvalorinicial.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        jTvalorinicial.setText("0");
        jPanel1.add(jTvalorinicial);
        jTvalorinicial.setBounds(20, 230, 130, 30);

        jTerror.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        jTerror.setText("0");
        jPanel1.add(jTerror);
        jTerror.setBounds(210, 230, 130, 30);

        jTer.setColumns(20);
        jTer.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jTer.setRows(5);
        jScrollPane1.setViewportView(jTer);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(290, 320, 240, 320);

        jLabel11.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 51));
        jLabel11.setText("Initial value:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 200, 110, 30);

        jTxxx.setColumns(20);
        jTxxx.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jTxxx.setRows(5);
        jScrollPane2.setViewportView(jTxxx);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 320, 240, 320);

        jLabel12.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 51));
        jLabel12.setText("X");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(120, 280, 40, 30);

        jBresetear.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jBresetear.setText("Reset");
        jBresetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBresetearActionPerformed(evt);
            }
        });
        jPanel1.add(jBresetear);
        jBresetear.setBounds(370, 670, 160, 40);

        jBrun.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jBrun.setText("Run");
        jBrun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrunActionPerformed(evt);
            }
        });
        jPanel1.add(jBrun);
        jBrun.setBounds(20, 670, 160, 40);

        jTx5.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        jTx5.setText("0");
        jPanel1.add(jTx5);
        jTx5.setBounds(100, 90, 50, 30);

        jLabel14.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 51));
        jLabel14.setText("x^5");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(150, 90, 30, 30);

        jTx4.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        jTx4.setText("0");
        jPanel1.add(jTx4);
        jTx4.setBounds(180, 90, 50, 30);

        jLabel15.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 51));
        jLabel15.setText("x^4");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(230, 90, 30, 30);

        jTx3.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        jTx3.setText("0");
        jPanel1.add(jTx3);
        jTx3.setBounds(260, 90, 50, 30);

        jLabel16.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 51));
        jLabel16.setText("x^3");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(310, 90, 30, 30);

        jTx2.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        jTx2.setText("0");
        jPanel1.add(jTx2);
        jTx2.setBounds(340, 90, 50, 30);

        jLabel17.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 51));
        jLabel17.setText("x^2");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(390, 90, 30, 30);

        jTx.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        jTx.setText("0");
        jPanel1.add(jTx);
        jTx.setBounds(420, 90, 50, 30);

        jLabel18.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 51));
        jLabel18.setText("x");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(470, 90, 10, 30);

        jTc.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        jTc.setText("0");
        jPanel1.add(jTc);
        jTc.setBounds(480, 90, 50, 30);

        jLabel19.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 51));
        jLabel19.setText("x^6");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(70, 90, 30, 30);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tercero/cat-3195180_1280.jpg"))); // NOI18N
        jLabel20.setText("jLabel20");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(0, 0, 570, 920);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRcActionPerformed
        if (jRc.isSelected() == false) {
            jTc.setEnabled(false);
        } else {
            jTc.setEnabled(true);
        }
    }//GEN-LAST:event_jRcActionPerformed

    private void jR4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR4ActionPerformed
        if (jR4.isSelected() == false) {
            jTx4.setEnabled(false);
        } else {
            jTx4.setEnabled(true);
        }
    }//GEN-LAST:event_jR4ActionPerformed

    private void jR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR3ActionPerformed
        if (jR3.isSelected() == false) {
            jTx3.setEnabled(false);
        } else {
            jTx3.setEnabled(true);
        }
    }//GEN-LAST:event_jR3ActionPerformed

    private void jR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR2ActionPerformed
        if (jR2.isSelected() == false) {
            jTx2.setEnabled(false);
        } else {
            jTx2.setEnabled(true);
        }
    }//GEN-LAST:event_jR2ActionPerformed

    private void jR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR1ActionPerformed
        if (jR1.isSelected() == false) {
            jTx.setEnabled(false);
        } else {
            jTx.setEnabled(true);
        }
    }//GEN-LAST:event_jR1ActionPerformed

    private void jBresetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBresetearActionPerformed
        jTc.setEnabled(false);
        jTx.setEnabled(false);
        jTx2.setEnabled(false);
        jTx3.setEnabled(false);
        jTx4.setEnabled(false);
        jTx5.setEnabled(false);
        jTx6.setEnabled(false);
        jR1.setSelected(false);
        jR2.setSelected(false);
        jR3.setSelected(false);
        jR4.setSelected(false);
        jR5.setSelected(false);
        jR6.setSelected(false);
        jRc.setSelected(false);
        jTxx.setText("0");
        jTx22.setText("0");
        jTx33.setText("0");
        jTx44.setText("0");
        jTx55.setText("0");
        jTcc.setText("0");
        jTx6.setText("0");
        jTc.setText("0");
        jTvalorinicial.setText("0");
        jTerror.setText("0");
        jTndecimales.setText("0");
        jTx.setText("0");
        jTx2.setText("0");
        jTx3.setText("0");
        jTx4.setText("0");
        jTx5.setText("0");
        jTxxx.setText("");
        jTer.setText("");
    }//GEN-LAST:event_jBresetearActionPerformed

    private void jBrunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrunActionPerformed
        double x6 = 0, x5 = 0, x4 = 0, x3 = 0, x2 = 0, x = 0, x1 = 0, x0 = 0, c = 0, error = 0, fx0 = 0, fx1 = 0, xi = 0, errorrelativo = 0, inicial = 0, newxi = 0;
        int ndecimales = 0, conta;
        double dx5 = 0, dx4 = 0, dx3 = 0, dx2 = 0, dx = 0, dc = 0;
        double newx5 = 0, newx4 = 0, newx3 = 0, newx2 = 0, newx1 = 0, newc = 0;
        if (jTx6.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de la X^6", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                x6 = Double.parseDouble(jTx6.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio de la X^6", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }////////////////////////////////////
        if (jTx5.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de la X^5", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                x5 = Double.parseDouble(jTx5.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio de la X^5", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }//////////////////////////////////
        if (jTx4.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de la X^4", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                x4 = Double.parseDouble(jTx4.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio de la X^4", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }//////////////////////////////////
        if (jTx3.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de la X^3", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                x3 = Double.parseDouble(jTx3.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio de la X^3", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }//////////////////////////////////
        if (jTx2.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de la X^2", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                x2 = Double.parseDouble(jTx2.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio de la X^2", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }//////////////////////////////////
        if (jTx.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de la X", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                x = Double.parseDouble(jTx.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio de la X", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }//////////////////////////////////
        if (jTc.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de la Constante", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                c = Double.parseDouble(jTc.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio de la Constante", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }//////////////////////////////////
        if (jTerror.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio del error", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                error = Double.parseDouble(jTerror.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio del error", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }//////////////////////////////////
        if (jTndecimales.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de los decimales", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                ndecimales = Integer.parseInt(jTndecimales.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio de los decimales", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }//////////////////////////////////
        if (jTvalorinicial.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de valor inicial", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                inicial = Integer.parseInt(jTvalorinicial.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros o quebrados en\nel espacio de valor inicial", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }//////////////////////////////////
        if (jTx55.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de la X^5", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                dx5 = Double.parseDouble(jTx55.getText());
            } catch (NumberFormatException e) {
            }
        }//////////////////////////////////
        if (jTx44.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de la X^4", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                dx4 = Double.parseDouble(jTx44.getText());
            } catch (NumberFormatException e) {
            }
        }//////////////////////////////////
        if (jTx33.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de la X^3", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                dx3 = Double.parseDouble(jTx33.getText());
            } catch (NumberFormatException e) {
            }
        }//////////////////////////////////
        if (jTx22.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de la X^2", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                dx2 = Double.parseDouble(jTx22.getText());
            } catch (NumberFormatException e) {
            }
        }//////////////////////////////////
        if (jTxx.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de la X", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                dx = Double.parseDouble(jTxx.getText());
            } catch (NumberFormatException e) {
            }
        }//////////////////////////////////
        if (jTcc.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Se encuentra vacio el espacio de la Constante", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                dc = Double.parseDouble(jTcc.getText());
            } catch (NumberFormatException e) {
            }
        }//////////////////////////////////
        if (jR1.isSelected() == true || jR2.isSelected() == true || jR3.isSelected() == true || jR4.isSelected() == true || jR5.isSelected() == true || jR6.isSelected() == true || jRc.isSelected() == true) {
            newx5 = x6 * Math.pow(6, 1);
            jTx55.setText(Double.toString(newx5));
            newx4 = x5 * Math.pow(5, 1);
            jTx44.setText(Double.toString(newx4));
            newx3 = x4 * Math.pow(4, 1);
            jTx33.setText(Double.toString(newx3));
            newx2 = x3 * Math.pow(3, 1);
            jTx22.setText(Double.toString(newx2));
            newx1 = x2 * Math.pow(2, 1);
            jTxx.setText(Double.toString(newx1));
            newc = x * Math.pow(1, 1);
            jTcc.setText(Double.toString(newc));
            conta = 1;
            do {
                fx0 = ((x6 * Math.pow(inicial, 6)) + (x5 * Math.pow(inicial, 5)) + (x4 * Math.pow(inicial, 4)) + (x3 * Math.pow(inicial, 3)) + (x2 * Math.pow(inicial, 2)) + (x * Math.pow(inicial, 1) + (c)));
                fx1 = ((newx5 * Math.pow(inicial, 5)) + (newx4 * Math.pow(x1, 4)) + (newx3 * Math.pow(inicial, 3)) + (newx2 * Math.pow(inicial, 2)) + (newx1 * Math.pow(inicial, 1) + (newc)));
                xi = (inicial - (fx0 / fx1));
                newxi = inicial;//newxi sera el viejo valor inicial
                inicial = xi;//inicial obtiene el valor de la xi
                errorrelativo = Math.abs(((inicial) - (newxi)) / inicial) * 100;
                BigDecimal equis = new BigDecimal(inicial);
                equis = equis.setScale(ndecimales, RoundingMode.HALF_UP);
                BigDecimal elerror = new BigDecimal(errorrelativo);
                elerror = elerror.setScale(ndecimales, RoundingMode.HALF_UP);
                jTxxx.append("X" + conta + "\t" + equis + "\n");
                jTer.append("X" + conta + "\t" + elerror + "\n");
                conta++;
            } while (errorrelativo >= error || conta >= 100);
        }

    }//GEN-LAST:event_jBrunActionPerformed

    private void jR6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR6ActionPerformed
        if (jR6.isSelected() == false) {
            jTx6.setEnabled(false);
        } else {
            jTx6.setEnabled(true);
        }
    }//GEN-LAST:event_jR6ActionPerformed

    private void jR5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR5ActionPerformed
        if (jR5.isSelected() == false) {
            jTx5.setEnabled(false);
        } else {
            jTx5.setEnabled(true);
        }
    }//GEN-LAST:event_jR5ActionPerformed

    private void jTx44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTx44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTx44ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(metodo_Newton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(metodo_Newton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(metodo_Newton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(metodo_Newton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                metodo_Newton pipi = new metodo_Newton();
                pipi.setVisible(true);
                pipi.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBresetear;
    private javax.swing.JButton jBrun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jR1;
    private javax.swing.JRadioButton jR2;
    private javax.swing.JRadioButton jR3;
    private javax.swing.JRadioButton jR4;
    private javax.swing.JRadioButton jR5;
    private javax.swing.JRadioButton jR6;
    private javax.swing.JRadioButton jRc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTc;
    private javax.swing.JTextField jTcc;
    private javax.swing.JTextArea jTer;
    private javax.swing.JTextField jTerror;
    private javax.swing.JTextField jTndecimales;
    private javax.swing.JTextField jTvalorinicial;
    private javax.swing.JTextField jTx;
    private javax.swing.JTextField jTx2;
    private javax.swing.JTextField jTx22;
    private javax.swing.JTextField jTx3;
    private javax.swing.JTextField jTx33;
    private javax.swing.JTextField jTx4;
    private javax.swing.JTextField jTx44;
    private javax.swing.JTextField jTx5;
    private javax.swing.JTextField jTx55;
    private javax.swing.JTextField jTx6;
    private javax.swing.JTextField jTxx;
    private javax.swing.JTextArea jTxxx;
    // End of variables declaration//GEN-END:variables

}
