/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pro;

import java.awt.Dimension;
import java.util.Objects;
import javax.swing.JOptionPane;

/**
 *
 * @author CAT
 */
public class Crearu extends javax.swing.JFrame {
    public static Crearu us = new Crearu();
    Login lo = new Login();
    public static String user;
    public static String contra1;
    public static String contra2;

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getContra1() {
        return contra1;
    }

    public void setContra1(String contra1) {
        this.contra1 = contra1;
    }

    public String getContra2() {
        return contra2;
    }

    public void setContra2(String contra2) {
        this.contra2 = contra2;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 79 * hash + Objects.hashCode(this.user);
        hash = 79 * hash + Objects.hashCode(this.contra1);
        hash = 79 * hash + Objects.hashCode(this.contra2);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Crearu other = (Crearu) obj;
        if (!Objects.equals(this.user, other.user)) {
            return false;
        }
        if (!Objects.equals(this.contra1, other.contra1)) {
            return false;
        }
        if (!Objects.equals(this.contra2, other.contra2)) {
            return false;
        }
        return true;
    }
    
    /**
     * Creates new form Crearu
     */
    public Crearu() {
        initComponents();
        this.setMaximumSize(new Dimension(459, 353));
        this.setMinimumSize(new Dimension(459, 353));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTuser = new javax.swing.JTextField();
        jPcontra2 = new javax.swing.JPasswordField();
        jPcontra1 = new javax.swing.JPasswordField();
        jBsalir = new javax.swing.JButton();
        jBcrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 51, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Confirmar contra:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 140, 130, 40);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 20, 80, 40);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Contraseña:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 80, 100, 40);

        jTuser.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jPanel2.add(jTuser);
        jTuser.setBounds(150, 20, 210, 40);

        jPcontra2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jPanel2.add(jPcontra2);
        jPcontra2.setBounds(150, 140, 210, 40);

        jPcontra1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jPanel2.add(jPcontra1);
        jPcontra1.setBounds(150, 80, 210, 40);

        jBsalir.setBackground(new java.awt.Color(51, 0, 153));
        jBsalir.setFont(new java.awt.Font("Dubai Light", 0, 12)); // NOI18N
        jBsalir.setText("SALIR");
        jBsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });
        jPanel2.add(jBsalir);
        jBsalir.setBounds(180, 200, 70, 30);

        jBcrear.setBackground(new java.awt.Color(51, 0, 153));
        jBcrear.setFont(new java.awt.Font("Dubai Light", 0, 12)); // NOI18N
        jBcrear.setText("CREAR");
        jBcrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcrearActionPerformed(evt);
            }
        });
        jPanel2.add(jBcrear);
        jBcrear.setBounds(270, 200, 70, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 30, 390, 250);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        JOptionPane.showMessageDialog(null, "¿Seguro que desea salir?", "Question", JOptionPane.QUESTION_MESSAGE);
        int input = JOptionPane.showOptionDialog(null, "Seleccion", "Selector de opciones", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new String[]{"Si", "NO",}, "Opcion 1");
        switch (input) {
            case 0:
                lo.setVisible(true);
                lo.setLocationRelativeTo(null);
                dispose();
                break;
            case 1:
                JOptionPane.showMessageDialog(null, "Has cancelado", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                break;
        }
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBcrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcrearActionPerformed
        us=new Crearu();
        if (jTuser.getText().trim().equals("")) {///////////////////////////////////////X///////////////////////////////
//                JOptionPane.showMessageDialog(null, "Favor de llenar el campo nombre");
        } else {
            try {
                us.setUser(jTuser.getText());//string a double
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo letras");
            }
        }
        if (jPcontra1.getText().trim().equals("")) {///////////////////////////////////////X///////////////////////////////
//                JOptionPane.showMessageDialog(null, "Favor de llenar el campo contraseña");
        } else {
            try {
                us.setContra1(jPcontra1.getText());//string a double
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo letras");
            }
        }
        if (jPcontra2.getText().trim().equals("")) {///////////////////////////////////////X///////////////////////////////
//                JOptionPane.showMessageDialog(null, "Favor de llenar el campo confirmar contraseña");
        } else {
            try {
                us.setContra2(jPcontra2.getText());//string a double
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo letras");
            }
        }
        if (us != null) {
            try {
                if (us.getContra1().equals(us.getContra2())) {
                    System.out.println(us.getUser());
                    System.out.println(us.getContra1());
                    System.out.println("///////////////////");
                    JOptionPane.showMessageDialog(null, "Usuario creado");
                    lo.setVisible(true);
                    lo.setLocationRelativeTo(null);
                    dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Favor de que ambas contraseñas coincidan");
                }
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(null, "Favor de llenar los campos de texto");
            }
        }
        

    }//GEN-LAST:event_jBcrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crearu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crearu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crearu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crearu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Crearu u = new Crearu();
                u.setVisible(true);
                u.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcrear;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPcontra1;
    private javax.swing.JPasswordField jPcontra2;
    private javax.swing.JTextField jTuser;
    // End of variables declaration//GEN-END:variables
}
