/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pro;

import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Objects;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author CAT
 */
public class Login extends javax.swing.JFrame {

    public static String use;
    public static String con;
    public static String use2;
    public static String con2;
    public static Crearu us = new Crearu();
    public static Login matbus = new Login();
    public static Ventanausuario ven = new Ventanausuario();
    public static Buscador bus = new Buscador();

    public String getUse() {
        return use;
    }

    public void setUse(String use) {
        this.use = use;
    }

    public String getCon() {
        return con;
    }

    public void setCon(String con) {
        this.con = con;
    }

    public String getUse2() {
        return use2;
    }

    public void setUse2(String use2) {
        this.use2 = use2;
    }

    public String getCon2() {
        return con2;
    }

    public void setCon2(String con2) {
        this.con2 = con2;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 67 * hash + Objects.hashCode(this.use);
        hash = 67 * hash + Objects.hashCode(this.con);
        hash = 67 * hash + Objects.hashCode(this.use2);
        hash = 67 * hash + Objects.hashCode(this.con2);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Login other = (Login) obj;
        if (!Objects.equals(this.use, other.use)) {
            return false;
        }
        if (!Objects.equals(this.con, other.con)) {
            return false;
        }
        if (!Objects.equals(this.use2, other.use2)) {
            return false;
        }
        if (!Objects.equals(this.con2, other.con2)) {
            return false;
        }
        return true;
    }

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setMaximumSize(new Dimension(410, 475));
        this.setMinimumSize(new Dimension(410, 475));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTusuario = new javax.swing.JTextField();
        jPcontra = new javax.swing.JPasswordField();
        jBingresar = new javax.swing.JButton();
        jLcrear = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 51, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LOGIN");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(110, 20, 60, 30);

        jTusuario.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        jPanel2.add(jTusuario);
        jTusuario.setBounds(30, 90, 220, 40);

        jPcontra.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        jPanel2.add(jPcontra);
        jPcontra.setBounds(30, 140, 220, 40);

        jBingresar.setBackground(new java.awt.Color(51, 0, 153));
        jBingresar.setFont(new java.awt.Font("Dubai Light", 0, 12)); // NOI18N
        jBingresar.setText("LOGIN");
        jBingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBingresarActionPerformed(evt);
            }
        });
        jPanel2.add(jBingresar);
        jBingresar.setBounds(80, 200, 120, 30);

        jLcrear.setBackground(new java.awt.Color(51, 0, 153));
        jLcrear.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLcrear.setForeground(new java.awt.Color(51, 0, 153));
        jLcrear.setText("Crear Usuario");
        jLcrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLcrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLcrearMouseClicked(evt);
            }
        });
        jPanel2.add(jLcrear);
        jLcrear.setBounds(90, 230, 100, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(60, 50, 280, 330);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jLcrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLcrearMouseClicked
        Crearu user = new Crearu();
        user.setVisible(true);
        user.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jLcrearMouseClicked

    private void jBingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBingresarActionPerformed
        try{
        if (us != null && matbus != null) {
            if (jTusuario.getText().trim().equals("")) {
//                JOptionPane.showMessageDialog(null, "Favor de poner el usuario", "Vacio", JOptionPane.INFORMATION_MESSAGE);
            } else {
                try {
                    matbus.setUse2(jTusuario.getText());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Favor de solo ingresar caracteres y no numeros", "Error", JOptionPane.WARNING_MESSAGE);
                }
            }
            if (jPcontra.getText().trim().equals("")) {
//                JOptionPane.showMessageDialog(null, "Favor de poner la contraseña", "Vacio", JOptionPane.INFORMATION_MESSAGE);
            } else {
                try {
                    matbus.setCon2(jPcontra.getText());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Favor de solo ingresar caracteres y no numeros en la ubicacion", "Error", JOptionPane.WARNING_MESSAGE);
                }
            }            
            if (matbus.getUse2().equals(us.getUser()) && matbus.getCon2().equals(us.getContra1())) {
                ven.setVisible(true);
                ven.setLocationRelativeTo(null);
                dispose();
            } else if (matbus.getUse2().equals("reclutador") && matbus.getCon2().equals("soyelboss")) {
                bus.setVisible(true);
                bus.setLocationRelativeTo(null);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuario no encontrado");
                JOptionPane.showMessageDialog(null, "Favor de crear un usuario");
            }
        }
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Favor de crear un usuario");
        }
        
        System.out.println(matbus.getUse2());
        System.out.println(us.getUser());
        System.out.println(us.getContra1());
//        if(use.equals("jefe") || con.equals("soychido")){
//            ven.setVisible(true);
//            dispose();
//        }
    }//GEN-LAST:event_jBingresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login log = new Login();
                log.setVisible(true);
                log.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLcrear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPcontra;
    private javax.swing.JTextField jTusuario;
    // End of variables declaration//GEN-END:variables
}
