/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pro;

import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author CAT
 */
public class Ventanausuario extends javax.swing.JFrame {

    /**
     * Creates new form Ventanausuario
     */
    public Ventanausuario() {
        initComponents();
        this.setMaximumSize(new Dimension(1239,842));
        this.setMinimumSize(new Dimension(1239,842));
        jPseguridad.setVisible(false);
        jPjava.setVisible(false);
        jPpython.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPpropuesta1 = new javax.swing.JPanel();
        jLsegu2 = new javax.swing.JLabel();
        jLsegu3 = new javax.swing.JLabel();
        jLsegu4 = new javax.swing.JLabel();
        jLsegu = new javax.swing.JLabel();
        jLsegu1 = new javax.swing.JLabel();
        jPpropuesta2 = new javax.swing.JPanel();
        jLjava = new javax.swing.JLabel();
        jLjava1 = new javax.swing.JLabel();
        jLjava2 = new javax.swing.JLabel();
        jLjava3 = new javax.swing.JLabel();
        jLjava4 = new javax.swing.JLabel();
        jPpropuesta3 = new javax.swing.JPanel();
        jLpython = new javax.swing.JLabel();
        jLpython1 = new javax.swing.JLabel();
        jLpython2 = new javax.swing.JLabel();
        jLpython3 = new javax.swing.JLabel();
        jLpython4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPjava = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jPseguridad = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPpython = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 51, 255));
        jPanel1.setLayout(null);

        jPpropuesta1.setBackground(new java.awt.Color(255, 255, 255));
        jPpropuesta1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPpropuesta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPpropuesta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPpropuesta1MouseClicked(evt);
            }
        });
        jPpropuesta1.setLayout(null);

        jLsegu2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLsegu2.setForeground(new java.awt.Color(0, 0, 0));
        jLsegu2.setText("Guadalajara Jalisco");
        jLsegu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLsegu2MouseClicked(evt);
            }
        });
        jPpropuesta1.add(jLsegu2);
        jLsegu2.setBounds(20, 70, 130, 20);

        jLsegu3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLsegu3.setForeground(new java.awt.Color(102, 102, 102));
        jLsegu3.setText("Salario mensual 6,800.  Ubicado:  Guadalajara Jalisco - Contrato por tiempo indefinido ");
        jLsegu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLsegu3MouseClicked(evt);
            }
        });
        jPpropuesta1.add(jLsegu3);
        jLsegu3.setBounds(20, 110, 480, 20);

        jLsegu4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLsegu4.setForeground(new java.awt.Color(102, 102, 102));
        jLsegu4.setText("Vigencia de la oferta: 30 de agosto de 2019...");
        jLsegu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLsegu4MouseClicked(evt);
            }
        });
        jPpropuesta1.add(jLsegu4);
        jLsegu4.setBounds(20, 130, 480, 20);

        jLsegu.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLsegu.setForeground(new java.awt.Color(0, 102, 255));
        jLsegu.setText("SEGURIDAD");
        jLsegu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLseguMouseClicked(evt);
            }
        });
        jPpropuesta1.add(jLsegu);
        jLsegu.setBounds(20, 10, 90, 40);

        jLsegu1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLsegu1.setForeground(new java.awt.Color(0, 0, 0));
        jLsegu1.setText("Rock & Dance");
        jLsegu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLsegu1MouseClicked(evt);
            }
        });
        jPpropuesta1.add(jLsegu1);
        jLsegu1.setBounds(20, 50, 100, 20);

        jPanel1.add(jPpropuesta1);
        jPpropuesta1.setBounds(0, 80, 530, 210);

        jPpropuesta2.setBackground(new java.awt.Color(255, 255, 255));
        jPpropuesta2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPpropuesta2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPpropuesta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPpropuesta2MouseClicked(evt);
            }
        });
        jPpropuesta2.setLayout(null);

        jLjava.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLjava.setForeground(new java.awt.Color(0, 102, 255));
        jLjava.setText("JAVA FULL STACK/DEVELOPER");
        jLjava.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLjavaMouseClicked(evt);
            }
        });
        jPpropuesta2.add(jLjava);
        jLjava.setBounds(20, 10, 230, 40);

        jLjava1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLjava1.setForeground(new java.awt.Color(0, 0, 0));
        jLjava1.setText("New Future Con");
        jLjava1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLjava1MouseClicked(evt);
            }
        });
        jPpropuesta2.add(jLjava1);
        jLjava1.setBounds(20, 50, 120, 20);

        jLjava2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLjava2.setForeground(new java.awt.Color(0, 0, 0));
        jLjava2.setText("Guadalajara Jalisco");
        jLjava2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLjava2MouseClicked(evt);
            }
        });
        jPpropuesta2.add(jLjava2);
        jLjava2.setBounds(20, 70, 130, 20);

        jLjava3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLjava3.setForeground(new java.awt.Color(102, 102, 102));
        jLjava3.setText("Salario mensual de 50,000 a 60,000 . Ubicado: Guadalajara Jalisco - Contrato permanente");
        jLjava3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLjava3MouseClicked(evt);
            }
        });
        jPpropuesta2.add(jLjava3);
        jLjava3.setBounds(20, 110, 490, 20);

        jLjava4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLjava4.setForeground(new java.awt.Color(102, 102, 102));
        jLjava4.setText("Vigencia de la oferta: 13 de septiembre de 2019...");
        jLjava4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLjava4MouseClicked(evt);
            }
        });
        jPpropuesta2.add(jLjava4);
        jLjava4.setBounds(20, 130, 480, 20);

        jPanel1.add(jPpropuesta2);
        jPpropuesta2.setBounds(0, 300, 530, 210);

        jPpropuesta3.setBackground(new java.awt.Color(255, 255, 255));
        jPpropuesta3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPpropuesta3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPpropuesta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPpropuesta3MouseClicked(evt);
            }
        });
        jPpropuesta3.setLayout(null);

        jLpython.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLpython.setForeground(new java.awt.Color(0, 102, 255));
        jLpython.setText("PYTHON FULL STACK");
        jLpython.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLpythonMouseClicked(evt);
            }
        });
        jPpropuesta3.add(jLpython);
        jLpython.setBounds(20, 10, 230, 40);

        jLpython1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLpython1.setForeground(new java.awt.Color(0, 0, 0));
        jLpython1.setText("New Future Con");
        jLpython1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLpython1MouseClicked(evt);
            }
        });
        jPpropuesta3.add(jLpython1);
        jLpython1.setBounds(20, 50, 120, 20);

        jLpython2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLpython2.setForeground(new java.awt.Color(0, 0, 0));
        jLpython2.setText("Guadalajara Jalisco");
        jLpython2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLpython2MouseClicked(evt);
            }
        });
        jPpropuesta3.add(jLpython2);
        jLpython2.setBounds(20, 70, 130, 20);

        jLpython3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLpython3.setForeground(new java.awt.Color(102, 102, 102));
        jLpython3.setText("Salario mensual de 80,000 a 88,000 . Ubicado: Guadalajara Jalisco - Contrato permanente");
        jLpython3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLpython3MouseClicked(evt);
            }
        });
        jPpropuesta3.add(jLpython3);
        jLpython3.setBounds(20, 110, 490, 20);

        jLpython4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLpython4.setForeground(new java.awt.Color(102, 102, 102));
        jLpython4.setText("Vigencia de la oferta: 31 de agosto de 2019...");
        jLpython4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLpython4MouseClicked(evt);
            }
        });
        jPpropuesta3.add(jLpython4);
        jLpython4.setBounds(20, 130, 480, 20);

        jPanel1.add(jPpropuesta3);
        jPpropuesta3.setBounds(0, 520, 530, 210);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("VACANTES DE TRABAJO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 30, 260, 40);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("POSTULARME");
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(993, 25, 190, 40);

        jPjava.setBackground(new java.awt.Color(204, 204, 204));
        jPjava.setLayout(null);

        jLabel27.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("-SQL/SqlServer");
        jPjava.add(jLabel27);
        jLabel27.setBounds(370, 420, 170, 30);

        jLabel58.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 0, 0));
        jLabel58.setText("-HTML, CSS");
        jPjava.add(jLabel58);
        jLabel58.setBounds(30, 420, 300, 30);

        jLabel59.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 0, 0));
        jLabel59.setText("-Angular");
        jPjava.add(jLabel59);
        jLabel59.setBounds(370, 390, 170, 30);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("JAVA DEVELOPER");
        jPjava.add(jLabel9);
        jLabel9.setBounds(30, 20, 160, 40);

        jLabel30.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Guadalajara, Jalisco");
        jPjava.add(jLabel30);
        jLabel30.setBounds(50, 60, 160, 30);

        jLabel67.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(0, 0, 0));
        jLabel67.setText("Salario de 50,000 a 60,000 mensuales");
        jPjava.add(jLabel67);
        jLabel67.setBounds(50, 90, 270, 30);

        jLabel68.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(0, 0, 0));
        jLabel68.setText("Descripción de la vacante");
        jPjava.add(jLabel68);
        jLabel68.setBounds(30, 120, 190, 30);

        jLabel69.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(0, 0, 0));
        jLabel69.setText("Contratación: Tiempo completo");
        jPjava.add(jLabel69);
        jLabel69.setBounds(30, 150, 230, 30);

        jLabel70.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(0, 0, 0));
        jLabel70.setText("Categoria: Tecnologías de la información / Sistemas, Desarrollador  de Software");
        jPjava.add(jLabel70);
        jLabel70.setBounds(30, 180, 560, 30);

        jLabel71.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(0, 0, 0));
        jLabel71.setText("New Future Con es una empresa dedicada al software conformada de un equipo");
        jPjava.add(jLabel71);
        jLabel71.setBounds(30, 210, 560, 30);

        jLabel72.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(0, 0, 0));
        jLabel72.setText("dedicado profesionalmente con más de 50 años de experiencia.");
        jPjava.add(jLabel72);
        jLabel72.setBounds(30, 240, 560, 30);

        jLabel73.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(0, 0, 0));
        jLabel73.setText("Estamos totalmente orgullosos de que gracias a nuestro servicio de calidad,");
        jPjava.add(jLabel73);
        jLabel73.setBounds(30, 270, 560, 30);

        jLabel74.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(0, 0, 0));
        jLabel74.setText("nuestros clientes confían en nosotros como socios comerciales. Las Soluciones ");
        jPjava.add(jLabel74);
        jLabel74.setBounds(30, 300, 560, 30);

        jLabel75.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(0, 0, 0));
        jLabel75.setText("innovadoreas en RH, Ingeniería y TI nos han ayudado a un crecimiento con el 100%.");
        jPjava.add(jLabel75);
        jLabel75.setBounds(30, 330, 580, 30);

        jLabel76.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(0, 0, 0));
        jLabel76.setText("Habilidades:");
        jPjava.add(jLabel76);
        jLabel76.setBounds(30, 360, 90, 30);

        jLabel77.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(0, 0, 0));
        jLabel77.setText("-Java Standar Edition, java EE, java (v.6 o 8)");
        jPjava.add(jLabel77);
        jLabel77.setBounds(30, 390, 300, 30);

        jLabel80.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(0, 0, 0));
        jLabel80.setText("Zona de trabajo:");
        jPjava.add(jLabel80);
        jLabel80.setBounds(30, 450, 120, 30);

        jLabel81.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(0, 0, 0));
        jLabel81.setText("Zona centro Guadalajara, Jalisco av juares #1322");
        jPjava.add(jLabel81);
        jLabel81.setBounds(150, 450, 450, 30);

        jLabel82.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(0, 0, 0));
        jLabel82.setText("-Lunes a Viernes");
        jPjava.add(jLabel82);
        jLabel82.setBounds(30, 480, 130, 30);

        jLabel83.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(0, 0, 0));
        jLabel83.setText("-9:00 am a 18:00 pm");
        jPjava.add(jLabel83);
        jLabel83.setBounds(30, 510, 150, 30);

        jLabel84.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(0, 0, 0));
        jLabel84.setText("Telefono:");
        jPjava.add(jLabel84);
        jLabel84.setBounds(30, 540, 70, 30);

        jLabel85.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(0, 0, 0));
        jLabel85.setText("3389769009");
        jPjava.add(jLabel85);
        jLabel85.setBounds(110, 540, 150, 30);

        jPanel1.add(jPjava);
        jPjava.setBounds(540, 80, 640, 650);

        jPseguridad.setBackground(new java.awt.Color(204, 204, 204));
        jPseguridad.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Zona de trabajo: ");
        jPseguridad.add(jLabel25);
        jLabel25.setBounds(30, 520, 120, 30);

        jLabel26.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("-Cuidado de los valores de la empresa");
        jPseguridad.add(jLabel26);
        jLabel26.setBounds(320, 390, 270, 30);

        jLabel28.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("somos una de las tiendas mas grandes del país, posicionándonos como uno de");
        jPseguridad.add(jLabel28);
        jLabel28.setBounds(30, 240, 560, 30);

        jLabel29.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("los líderes del mercado y como una de las mejores empresas para trabajar en ");
        jPseguridad.add(jLabel29);
        jLabel29.setBounds(30, 270, 560, 30);

        jLabel31.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("México, ven y atrevete a formar parte de nuestra historia.");
        jPseguridad.add(jLabel31);
        jLabel31.setBounds(30, 300, 560, 30);

        jLabel32.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("-Disponibilidad de horario");
        jPseguridad.add(jLabel32);
        jLabel32.setBounds(320, 460, 260, 30);

        jLabel33.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("-Revisar las devoluciones");
        jPseguridad.add(jLabel33);
        jLabel33.setBounds(30, 390, 210, 30);

        jLabel34.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("-Hacer revisiones de PCI");
        jPseguridad.add(jLabel34);
        jLabel34.setBounds(320, 360, 210, 30);

        jLabel35.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Funciones:");
        jPseguridad.add(jLabel35);
        jLabel35.setBounds(30, 330, 80, 30);

        jLabel36.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("-Revisión de personal interno.");
        jPseguridad.add(jLabel36);
        jLabel36.setBounds(30, 360, 210, 30);

        jLabel37.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("-Integridad y actitud de servicio");
        jPseguridad.add(jLabel37);
        jLabel37.setBounds(320, 490, 260, 30);

        jLabel38.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("-Preparatoria terminada (certificada)");
        jPseguridad.add(jLabel38);
        jLabel38.setBounds(30, 460, 260, 30);

        jLabel39.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Télefono: 3820194013");
        jPseguridad.add(jLabel39);
        jLabel39.setBounds(30, 600, 250, 30);

        jLabel40.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Requisitos:");
        jPseguridad.add(jLabel40);
        jLabel40.setBounds(30, 430, 80, 30);

        jLabel41.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("-Paqueteria Office básico");
        jPseguridad.add(jLabel41);
        jLabel41.setBounds(30, 490, 260, 30);

        jLabel42.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Rock & Dance Galerías Santa Anita (Tlajomulco de Zuñoga)");
        jPseguridad.add(jLabel42);
        jLabel42.setBounds(150, 520, 410, 30);

        jLabel43.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("1.-Hotel Presidente Intercontinental: Av. López Mateos, esq. Av Moctezuma Zap, Jal.");
        jPseguridad.add(jLabel43);
        jLabel43.setBounds(30, 550, 590, 30);

        jLabel44.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Horarios de Oficina de Reclutamiento:");
        jPseguridad.add(jLabel44);
        jLabel44.setBounds(30, 580, 270, 30);

        jLabel45.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Lunes a viernes de 9:30 a 18:00 hrs");
        jPseguridad.add(jLabel45);
        jLabel45.setBounds(320, 580, 250, 30);

        jLabel46.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("Sábado de 9:30 a 13:00 hrs");
        jPseguridad.add(jLabel46);
        jLabel46.setBounds(320, 600, 250, 30);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("SEGURIDAD");
        jPseguridad.add(jLabel8);
        jLabel8.setBounds(30, 20, 120, 40);

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Guadalajara, Jalisco");
        jPseguridad.add(jLabel20);
        jLabel20.setBounds(50, 60, 160, 30);

        jLabel24.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Salario de 6,800 mensuales");
        jPseguridad.add(jLabel24);
        jLabel24.setBounds(50, 90, 200, 30);

        jLabel47.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Descripción de la vacante");
        jPseguridad.add(jLabel47);
        jLabel47.setBounds(30, 120, 190, 30);

        jLabel48.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Contratación: Tiempo completo");
        jPseguridad.add(jLabel48);
        jLabel48.setBounds(30, 150, 230, 30);

        jLabel49.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Categoria: Seguridad");
        jPseguridad.add(jLabel49);
        jLabel49.setBounds(30, 180, 150, 30);

        jLabel50.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("Rock &  Dance te invita a formar parte de su gran equipo de trabajo, formamos");
        jPseguridad.add(jLabel50);
        jLabel50.setBounds(30, 210, 560, 30);

        jPanel1.add(jPseguridad);
        jPseguridad.setBounds(540, 80, 660, 650);

        jPpython.setBackground(new java.awt.Color(204, 204, 204));
        jPpython.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("PYTHON DEVELOPER");
        jPpython.add(jLabel7);
        jLabel7.setBounds(40, 20, 180, 40);

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Guadalajara, Jalisco");
        jPpython.add(jLabel19);
        jLabel19.setBounds(60, 60, 160, 30);

        jLabel21.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Salario de 50,000 a 60,000 mensuales");
        jPpython.add(jLabel21);
        jLabel21.setBounds(60, 90, 270, 30);

        jLabel55.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 0, 0));
        jLabel55.setText("Descripción de la vacante");
        jPpython.add(jLabel55);
        jLabel55.setBounds(40, 110, 190, 30);

        jLabel22.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Contratación: Tiempo completo");
        jPpython.add(jLabel22);
        jLabel22.setBounds(40, 140, 230, 30);

        jLabel23.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Categoria: Tecnologías de la información / Sistemas, Desarrollador  de Software");
        jPpython.add(jLabel23);
        jLabel23.setBounds(40, 170, 560, 30);

        jLabel51.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 0));
        jLabel51.setText("New Future Con es una empresa dedicada al software conformada de un equipo");
        jPpython.add(jLabel51);
        jLabel51.setBounds(40, 200, 560, 30);

        jLabel52.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 0, 0));
        jLabel52.setText("dedicado profesionalmente con más de 50 años de experiencia.");
        jPpython.add(jLabel52);
        jLabel52.setBounds(40, 230, 560, 30);

        jLabel53.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 0, 0));
        jLabel53.setText("Estamos totalmente orgullosos de que gracias a nuestro servicio de calidad,");
        jPpython.add(jLabel53);
        jLabel53.setBounds(40, 260, 560, 30);

        jLabel54.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 0, 0));
        jLabel54.setText("nuestros clientes confían en nosotros como socios comerciales. Las Soluciones ");
        jPpython.add(jLabel54);
        jLabel54.setBounds(40, 290, 560, 30);

        jLabel56.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 0, 0));
        jLabel56.setText("innovadoreas en RH, Ingeniería y TI nos han ayudado a un crecimiento con el 100%.");
        jPpython.add(jLabel56);
        jLabel56.setBounds(40, 320, 580, 30);

        jLabel61.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 0, 0));
        jLabel61.setText("Habilidades:");
        jPpython.add(jLabel61);
        jLabel61.setBounds(40, 350, 90, 30);

        jLabel62.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(0, 0, 0));
        jLabel62.setText("-Base de datos: Postgress, Sql Mongob");
        jPpython.add(jLabel62);
        jLabel62.setBounds(40, 440, 300, 30);

        jLabel78.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(0, 0, 0));
        jLabel78.setText("-Back end: Django(python) o MEAN stack");
        jPpython.add(jLabel78);
        jLabel78.setBounds(40, 380, 300, 30);

        jLabel79.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(0, 0, 0));
        jLabel79.setText("Front end: React, Angular, Vue js");
        jPpython.add(jLabel79);
        jLabel79.setBounds(40, 410, 300, 30);

        jLabel66.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(0, 0, 0));
        jLabel66.setText("Zona de trabajo:");
        jPpython.add(jLabel66);
        jLabel66.setBounds(40, 470, 120, 30);

        jLabel63.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(0, 0, 0));
        jLabel63.setText("Zona centro Guadalajara, Jalisco av juares #1322");
        jPpython.add(jLabel63);
        jLabel63.setBounds(160, 470, 450, 30);

        jLabel64.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(0, 0, 0));
        jLabel64.setText("-Lunes a Viernes");
        jPpython.add(jLabel64);
        jLabel64.setBounds(40, 500, 130, 30);

        jLabel65.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(0, 0, 0));
        jLabel65.setText("-9:00 am a 18:00 pm");
        jPpython.add(jLabel65);
        jLabel65.setBounds(40, 530, 150, 30);

        jLabel60.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 0, 0));
        jLabel60.setText("Telefono:");
        jPpython.add(jLabel60);
        jLabel60.setBounds(40, 560, 70, 30);

        jLabel57.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 0, 0));
        jLabel57.setText("3389769009");
        jPpython.add(jLabel57);
        jLabel57.setBounds(120, 560, 150, 30);

        jPanel1.add(jPpython);
        jPpython.setBounds(540, 80, 660, 650);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLseguMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLseguMouseClicked
        if(jPpropuesta1.isEnabled() || jLsegu.isEnabled() || jLsegu1.isEnabled() || jLsegu2.isEnabled() || jLsegu3.isEnabled() || jLsegu4.isEnabled()){
            jPseguridad.setVisible(true);
            jPjava.setVisible(false);
            jPpython.setVisible(false);
        }
    }//GEN-LAST:event_jLseguMouseClicked

    private void jLsegu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLsegu1MouseClicked
         if(jPpropuesta1.isEnabled() || jLsegu.isEnabled() || jLsegu1.isEnabled() || jLsegu2.isEnabled() || jLsegu3.isEnabled() || jLsegu4.isEnabled()){
            jPseguridad.setVisible(true);
            jPjava.setVisible(false);
            jPpython.setVisible(false);
        }
    }//GEN-LAST:event_jLsegu1MouseClicked

    private void jLsegu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLsegu2MouseClicked
         if(jPpropuesta1.isEnabled() || jLsegu.isEnabled() || jLsegu1.isEnabled() || jLsegu2.isEnabled() || jLsegu3.isEnabled() || jLsegu4.isEnabled()){
            jPseguridad.setVisible(true);
            jPjava.setVisible(false);
            jPpython.setVisible(false);
        }
    }//GEN-LAST:event_jLsegu2MouseClicked

    private void jLsegu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLsegu3MouseClicked
         if(jPpropuesta1.isEnabled() || jLsegu.isEnabled() || jLsegu1.isEnabled() || jLsegu2.isEnabled() || jLsegu3.isEnabled() || jLsegu4.isEnabled()){
            jPseguridad.setVisible(true);
            jPjava.setVisible(false);
            jPpython.setVisible(false);
        }
    }//GEN-LAST:event_jLsegu3MouseClicked

    private void jLsegu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLsegu4MouseClicked
         if(jPpropuesta1.isEnabled() || jLsegu.isEnabled() || jLsegu1.isEnabled() || jLsegu2.isEnabled() || jLsegu3.isEnabled() || jLsegu4.isEnabled()){
            jPseguridad.setVisible(true);
            jPjava.setVisible(false);
            jPpython.setVisible(false);
        }
    }//GEN-LAST:event_jLsegu4MouseClicked

    private void jPpropuesta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPpropuesta1MouseClicked
         if(jPpropuesta1.isEnabled() || jLsegu.isEnabled() || jLsegu1.isEnabled() || jLsegu2.isEnabled() || jLsegu3.isEnabled() || jLsegu4.isEnabled()){
            jPseguridad.setVisible(true);
            jPjava.setVisible(false);
            jPpython.setVisible(false);
        }
    }//GEN-LAST:event_jPpropuesta1MouseClicked

    private void jLjavaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLjavaMouseClicked
        if(jPpropuesta2.isEnabled() || jLjava.isEnabled() || jLjava1.isEnabled() || jLjava2.isEnabled() || jLjava3.isEnabled() || jLjava4.isEnabled()){
            jPseguridad.setVisible(false);
            jPjava.setVisible(true);
            jPpython.setVisible(false);
        }
    }//GEN-LAST:event_jLjavaMouseClicked

    private void jLjava1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLjava1MouseClicked
         if(jPpropuesta2.isEnabled() || jLjava.isEnabled() || jLjava1.isEnabled() || jLjava2.isEnabled() || jLjava3.isEnabled() || jLjava4.isEnabled()){
            jPseguridad.setVisible(false);
            jPjava.setVisible(true);
            jPpython.setVisible(false);
        }
    }//GEN-LAST:event_jLjava1MouseClicked

    private void jLjava2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLjava2MouseClicked
         if(jPpropuesta2.isEnabled() || jLjava.isEnabled() || jLjava1.isEnabled() || jLjava2.isEnabled() || jLjava3.isEnabled() || jLjava4.isEnabled()){
            jPseguridad.setVisible(false);
            jPjava.setVisible(true);
            jPpython.setVisible(false);
        }
    }//GEN-LAST:event_jLjava2MouseClicked

    private void jLjava3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLjava3MouseClicked
         if(jPpropuesta2.isEnabled() || jLjava.isEnabled() || jLjava1.isEnabled() || jLjava2.isEnabled() || jLjava3.isEnabled() || jLjava4.isEnabled()){
            jPseguridad.setVisible(false);
            jPjava.setVisible(true);
            jPpython.setVisible(false);
        }
    }//GEN-LAST:event_jLjava3MouseClicked

    private void jLjava4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLjava4MouseClicked
         if(jPpropuesta2.isEnabled() || jLjava.isEnabled() || jLjava1.isEnabled() || jLjava2.isEnabled() || jLjava3.isEnabled() || jLjava4.isEnabled()){
            jPseguridad.setVisible(false);
            jPjava.setVisible(true);
            jPpython.setVisible(false);
        }
    }//GEN-LAST:event_jLjava4MouseClicked

    private void jPpropuesta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPpropuesta2MouseClicked
         if(jPpropuesta2.isEnabled() || jLjava.isEnabled() || jLjava1.isEnabled() || jLjava2.isEnabled() || jLjava3.isEnabled() || jLjava4.isEnabled()){
            jPseguridad.setVisible(false);
            jPjava.setVisible(true);
            jPpython.setVisible(false);
        }
    }//GEN-LAST:event_jPpropuesta2MouseClicked

    private void jLpythonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLpythonMouseClicked
        if(jPpropuesta3.isEnabled() || jLpython.isEnabled() || jLpython1.isEnabled() || jLpython2.isEnabled() || jLpython3.isEnabled() || jLpython4.isEnabled()){
            jPseguridad.setVisible(false);
            jPjava.setVisible(false);
            jPpython.setVisible(true);
        }
    }//GEN-LAST:event_jLpythonMouseClicked

    private void jLpython1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLpython1MouseClicked
        if(jPpropuesta3.isEnabled() || jLpython.isEnabled() || jLpython1.isEnabled() || jLpython2.isEnabled() || jLpython3.isEnabled() || jLpython4.isEnabled()){
            jPseguridad.setVisible(false);
            jPjava.setVisible(false);
            jPpython.setVisible(true);
        }
    }//GEN-LAST:event_jLpython1MouseClicked

    private void jLpython2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLpython2MouseClicked
        if(jPpropuesta3.isEnabled() || jLpython.isEnabled() || jLpython1.isEnabled() || jLpython2.isEnabled() || jLpython3.isEnabled() || jLpython4.isEnabled()){
            jPseguridad.setVisible(false);
            jPjava.setVisible(false);
            jPpython.setVisible(true);
        }
    }//GEN-LAST:event_jLpython2MouseClicked

    private void jLpython3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLpython3MouseClicked
        if(jPpropuesta3.isEnabled() || jLpython.isEnabled() || jLpython1.isEnabled() || jLpython2.isEnabled() || jLpython3.isEnabled() || jLpython4.isEnabled()){
            jPseguridad.setVisible(false);
            jPjava.setVisible(false);
            jPpython.setVisible(true);
        }
    }//GEN-LAST:event_jLpython3MouseClicked

    private void jLpython4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLpython4MouseClicked
        if(jPpropuesta3.isEnabled() || jLpython.isEnabled() || jLpython1.isEnabled() || jLpython2.isEnabled() || jLpython3.isEnabled() || jLpython4.isEnabled()){
            jPseguridad.setVisible(false);
            jPjava.setVisible(false);
            jPpython.setVisible(true);
        }
    }//GEN-LAST:event_jLpython4MouseClicked

    private void jPpropuesta3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPpropuesta3MouseClicked
        if(jPpropuesta3.isEnabled() || jLpython.isEnabled() || jLpython1.isEnabled() || jLpython2.isEnabled() || jLpython3.isEnabled() || jLpython4.isEnabled()){
            jPseguridad.setVisible(false);
            jPjava.setVisible(false);
            jPpython.setVisible(true);
        }
    }//GEN-LAST:event_jPpropuesta3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Crearu u=new Crearu();
        Llenadodedatos datos=new Llenadodedatos();
        if(jPjava.isVisible()==true || jPpython.isVisible()==true || jPseguridad.isVisible()==true){
          datos.setVisible(true);
          datos.setLocationRelativeTo(null);
          dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Favor de seleccionar un trabajo","",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventanausuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventanausuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventanausuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventanausuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventanausuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLjava;
    private javax.swing.JLabel jLjava1;
    private javax.swing.JLabel jLjava2;
    private javax.swing.JLabel jLjava3;
    private javax.swing.JLabel jLjava4;
    private javax.swing.JLabel jLpython;
    private javax.swing.JLabel jLpython1;
    private javax.swing.JLabel jLpython2;
    private javax.swing.JLabel jLpython3;
    private javax.swing.JLabel jLpython4;
    private javax.swing.JLabel jLsegu;
    private javax.swing.JLabel jLsegu1;
    private javax.swing.JLabel jLsegu2;
    private javax.swing.JLabel jLsegu3;
    private javax.swing.JLabel jLsegu4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPjava;
    private javax.swing.JPanel jPpropuesta1;
    private javax.swing.JPanel jPpropuesta2;
    private javax.swing.JPanel jPpropuesta3;
    private javax.swing.JPanel jPpython;
    private javax.swing.JPanel jPseguridad;
    // End of variables declaration//GEN-END:variables
}
