/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Final;

import java.awt.Dimension;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JOptionPane;

/**
 *
 * @author CAT
 */
public class Gaussseidel extends javax.swing.JFrame {

    public static double x1, x2, x3, y1, y2, y3, z1, z2, z3, error, res1, res2, res3, fun1, fun2, fun3, rex, rey, rez, pm;
    public static int deci, conta = 1;
    public static double newxx, newyy, newzz, fun11, fun22, fun33, err, e1, e2, e3, e11, e22, e33;

    /**
     * Creates new form Gaussseidel
     */
    public Gaussseidel() {
        initComponents();
        this.setMaximumSize(new Dimension(790, 594));
        this.setMinimumSize(new Dimension(790, 594));
        jTventanilla.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTres3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTx3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTy3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTz3 = new javax.swing.JTextField();
        jTx1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTy1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTz1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTerror = new javax.swing.JTextField();
        jTx2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTy2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTz2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTres2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTres1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTndecimales = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTventanilla = new javax.swing.JTextArea();
        jBejecutar = new javax.swing.JButton();
        jBlimpiar1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jTres3.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jPanel1.add(jTres3);
        jTres3.setBounds(240, 120, 50, 40);

        jLabel1.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel1.setText("Z=");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 120, 30, 40);

        jTx3.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jPanel1.add(jTx3);
        jTx3.setBounds(20, 120, 50, 40);

        jLabel2.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel2.setText("X");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 120, 20, 40);

        jTy3.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jPanel1.add(jTy3);
        jTy3.setBounds(90, 120, 50, 40);

        jLabel3.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel3.setText("Y");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 120, 20, 40);

        jTz3.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jPanel1.add(jTz3);
        jTz3.setBounds(160, 120, 50, 40);

        jTx1.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jPanel1.add(jTx1);
        jTx1.setBounds(20, 20, 50, 40);

        jLabel4.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel4.setText("X");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 20, 20, 40);

        jTy1.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jPanel1.add(jTy1);
        jTy1.setBounds(90, 20, 50, 40);

        jLabel5.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel5.setText("Y");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(140, 20, 20, 40);

        jTz1.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jPanel1.add(jTz1);
        jTz1.setBounds(160, 20, 50, 40);

        jLabel6.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel6.setText("      % error:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(360, 70, 110, 40);

        jTerror.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jPanel1.add(jTerror);
        jTerror.setBounds(480, 70, 270, 40);

        jTx2.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jPanel1.add(jTx2);
        jTx2.setBounds(20, 70, 50, 40);

        jLabel7.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel7.setText("X");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 70, 20, 40);

        jTy2.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jPanel1.add(jTy2);
        jTy2.setBounds(90, 70, 50, 40);

        jLabel8.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel8.setText("Y");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(140, 70, 20, 40);

        jTz2.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jPanel1.add(jTz2);
        jTz2.setBounds(160, 70, 50, 40);

        jLabel9.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel9.setText("Z=");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(210, 70, 30, 40);

        jTres2.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jPanel1.add(jTres2);
        jTres2.setBounds(240, 70, 50, 40);

        jLabel10.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel10.setText("Z=");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(210, 20, 30, 40);

        jTres1.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jPanel1.add(jTres1);
        jTres1.setBounds(240, 20, 50, 40);

        jLabel11.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel11.setText("N°Decimales:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(360, 20, 110, 40);

        jTndecimales.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jPanel1.add(jTndecimales);
        jTndecimales.setBounds(480, 20, 270, 40);

        jTventanilla.setColumns(20);
        jTventanilla.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jTventanilla.setRows(5);
        jScrollPane1.setViewportView(jTventanilla);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 730, 290);

        jBejecutar.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jBejecutar.setText("Ejecutar");
        jBejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBejecutarActionPerformed(evt);
            }
        });
        jPanel1.add(jBejecutar);
        jBejecutar.setBounds(640, 500, 110, 40);

        jBlimpiar1.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jBlimpiar1.setText("Limpiar");
        jBlimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimpiar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBlimpiar1);
        jBlimpiar1.setBounds(20, 500, 110, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final/gummibarchen-318362_1280.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(-170, -40, 960, 570);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBejecutarActionPerformed
        if (jTx1.getText().trim().equals("")) {///////////////////////////////////////X///////////////////////////////
            JOptionPane.showMessageDialog(null, "x de la primera funcion se encuentra vacia");
        } else {
            try {
                x1 = Double.parseDouble(jTx1.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en la x");
            }
        }
        if (jTx2.getText().trim().equals("")) {///////////////////////////////////////X///////////////////////////////
            JOptionPane.showMessageDialog(null, "x de la segunda funcion se encuentra vacia");
        } else {
            try {
                x2 = Double.parseDouble(jTx2.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en la x");
            }
        }
        if (jTx3.getText().trim().equals("")) {///////////////////////////////////////X///////////////////////////////
            JOptionPane.showMessageDialog(null, "x de la tercera funcion se encuentra vacia");
        } else {
            try {
                x3 = Double.parseDouble(jTx3.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en la x");
            }
        }
        if (jTy1.getText().trim().equals("")) {///////////////////////////////////////X///////////////////////////////
            JOptionPane.showMessageDialog(null, "y de la primera funcion se encuentra vacia");
        } else {
            try {
                y1 = Double.parseDouble(jTy1.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en la y");
            }
        }
        if (jTy2.getText().trim().equals("")) {///////////////////////////////////////X///////////////////////////////
            JOptionPane.showMessageDialog(null, "y de la segunda funcion se encuentra vacia");
        } else {
            try {
                y2 = Double.parseDouble(jTy2.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en la y");
            }
        }
        if (jTy3.getText().trim().equals("")) {///////////////////////////////////////X///////////////////////////////
            JOptionPane.showMessageDialog(null, "y de la tercera funcion se encuentra vacia");
        } else {
            try {
                y3 = Double.parseDouble(jTy3.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en la y");
            }
        }
        if (jTz1.getText().trim().equals("")) {///////////////////////////////////////X///////////////////////////////
            JOptionPane.showMessageDialog(null, "z de la primera funcion se encuentra vacia");
        } else {
            try {
                z1 = Double.parseDouble(jTz1.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en la z");
            }
        }
        if (jTz2.getText().trim().equals("")) {///////////////////////////////////////X///////////////////////////////
            JOptionPane.showMessageDialog(null, "z de la segunda funcion se encuentra vacia");
        } else {
            try {
                z2 = Double.parseDouble(jTz2.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en la z");
            }
        }
        if (jTz3.getText().trim().equals("")) {///////////////////////////////////////X///////////////////////////////
            JOptionPane.showMessageDialog(null, "z de la tercera funcion se encuentra vacia");
        } else {
            try {
                z3 = Double.parseDouble(jTz3.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en la z");
            }
        }
        if (jTres1.getText().trim().equals("")) {///////////////////////////////////////X///////////////////////////////
            JOptionPane.showMessageDialog(null, "res de la primera funcion se encuentra vacia");
        } else {
            try {
                res1 = Double.parseDouble(jTres1.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en la res");
            }
        }
        if (jTres2.getText().trim().equals("")) {///////////////////////////////////////X///////////////////////////////
            JOptionPane.showMessageDialog(null, "res de la segunda funcion se encuentra vacia");
        } else {
            try {
                res2 = Double.parseDouble(jTres2.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en la res");
            }
        }
        if (jTres3.getText().trim().equals("")) {///////////////////////////////////////X///////////////////////////////
            JOptionPane.showMessageDialog(null, "res de la tercera funcion se encuentra vacia");
        } else {
            try {
                res3 = Double.parseDouble(jTres3.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en la res");
            }
        }
        if (jTndecimales.getText().trim().equals("")) {///////////////////////////////////////X///////////////////////////////
            JOptionPane.showMessageDialog(null, "Favor de ingresar el numero de decimales");
        } else {
            try {
                deci = Integer.parseInt(jTndecimales.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en el cuadro de los decimales");
            }
        }
        if (jTerror.getText().trim().equals("")) {///////////////////////////////////////X///////////////////////////////
            JOptionPane.showMessageDialog(null, "Favor de ingresar el error");
        } else {
            try {
                error = Double.parseDouble(jTerror.getText());//string a double
            } catch (NumberFormatException e) {

            }
        }
        //DESPEJE Y EVALUAR CON 0
        conta=1;
        rex = (res1 - (y1 * (0)) - (z1 * (0))) / x1;
        rey = (res2 - (x2 * rex) - (z2 * (0))) / y2;
        rez = (res3 - (x3 * rex) - (y3 * rey)) / z3;
        System.out.println("1 " + rex);
        System.out.println("2 " + rey);
        System.out.println("3 " + rez);
        do {
            fun1 = x1 * (rex) + y1 * (rey) + z1 * (rez);
            fun2 = x2 * (rex) + y2 * (rey) + z2 * (rez);
            fun3 = x3 * (rex) + y3 * (rey) + z3 * (rez);

            //PASARLOS EN VARIABLES DOUBLE PARA
            System.out.println("fun 1 " + fun1);
            System.out.println("fun 2 " + fun2);
            System.out.println("fun 3 " + fun3);
            //EVALUO
            e1 = Math.abs(((res1 - fun1) / res1) * 100);
            System.out.println("e11 " + e1);
            //EVALUO
            e2 = Math.abs(((res2 - fun2) / res2) * 100);
            System.out.println("e22 " + e2);
            //EVALUO
            e3 = Math.abs(((res3 - fun3) / res3) * 100);
            System.out.println("e33 " + e3);
            //EVALUO DE NUEVO CON PM
            pm = (e1 + e2 + e3) / 3;
            System.out.println("pm " + pm);
            BigDecimal xx = new BigDecimal(rex);
            xx = xx.setScale(deci, RoundingMode.HALF_UP);
            BigDecimal yy = new BigDecimal(rey);
            yy = yy.setScale(deci, RoundingMode.HALF_UP);
            BigDecimal zz = new BigDecimal(rez);
            zz = zz.setScale(deci, RoundingMode.HALF_UP);
            BigDecimal p = new BigDecimal(pm);
            p = p.setScale(deci, RoundingMode.HALF_UP);
            newxx=xx.doubleValue();
            newyy=yy.doubleValue();
            newzz=zz.doubleValue();
            err=p.doubleValue();
            jTventanilla.append("Iteracion" + conta + "\tx=" + newxx + "\ty=" + newyy + "\tz=" + newzz + "\ter=" + err + "\n");
            conta++;
            //ITERACION CHIDA
            rex = (res1 - (y1 * (rey)) - (z1 * (rez))) / x1;
            rey = (res2 - (x2 * (rex)) - (z2 * (rez))) / y2;
            rez = (res3 - (x3 * (rex)) - (y3 * (rey))) / z3;
            System.out.println("///////////////////////////\n1 " + rex);
            System.out.println("2 " + rey);
            System.out.println("3 " + rez);
        } while (pm > error || conta > 100);
    }//GEN-LAST:event_jBejecutarActionPerformed

    private void jBlimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimpiar1ActionPerformed
        jTx1.setText("");
        jTx2.setText("");
        jTx3.setText("");
        jTy1.setText("");
        jTy2.setText("");
        jTy3.setText("");
        jTz1.setText("");
        jTz2.setText("");
        jTz3.setText("");
        jTndecimales.setText("");
        jTerror.setText("");
        jTventanilla.setText("");
        jTres1.setText("");
        jTres2.setText("");
        jTres3.setText("");
    }//GEN-LAST:event_jBlimpiar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gaussseidel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gaussseidel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gaussseidel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gaussseidel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
                Gaussseidel gaus=new Gaussseidel();
                gaus.setVisible(true);
                gaus.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBejecutar;
    private javax.swing.JButton jBlimpiar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTerror;
    private javax.swing.JTextField jTndecimales;
    private javax.swing.JTextField jTres1;
    private javax.swing.JTextField jTres2;
    private javax.swing.JTextField jTres3;
    private javax.swing.JTextArea jTventanilla;
    private javax.swing.JTextField jTx1;
    private javax.swing.JTextField jTx2;
    private javax.swing.JTextField jTx3;
    private javax.swing.JTextField jTy1;
    private javax.swing.JTextField jTy2;
    private javax.swing.JTextField jTy3;
    private javax.swing.JTextField jTz1;
    private javax.swing.JTextField jTz2;
    private javax.swing.JTextField jTz3;
    // End of variables declaration//GEN-END:variables
}
