/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Final;

import java.awt.Dimension;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author CAT
 */
public class Metodoresiduos extends javax.swing.JFrame {

    ArrayList<String> al = new ArrayList<String>();
    public int i, d, conta = 1, ndecimales;
    public double x6, x5, x4, x3, x2, x, c, errorre, x0, x1, xi, er;
    public double rex6, rex5, rex4, rex3, rex2, rex, rec, rex66, rex55, rex44, rex33, rex22, rexx, recc;
    public double arrex[] = new double[1], arrex1[] = new double[7], arrex0[] = new double[7], arres2x1[] = new double[7], intervalo[] = new double[2];

    /**
     * Creates new form Metodoresiduos
     */
    public Metodoresiduos() {
        initComponents();
        this.setMaximumSize(new Dimension(525, 610));
        this.setMinimumSize(new Dimension(525, 610));
        jTc.setEnabled(false);
        jTx.setEnabled(false);
        jTx2.setEnabled(false);
        jTx3.setEnabled(false);
        jTx4.setEnabled(false);
        jTx5.setEnabled(false);
        jTx6.setEnabled(false);
        jTvalorer.setEnabled(false);
        jTvalorx.setEnabled(false);
        jTx0.setEnabled(false);
        jTx1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTx = new javax.swing.JTextField();
        jTx6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTx1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTx4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTx3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTx2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTc = new javax.swing.JTextField();
        jRc = new javax.swing.JRadioButton();
        jR6 = new javax.swing.JRadioButton();
        jR5 = new javax.swing.JRadioButton();
        jR4 = new javax.swing.JRadioButton();
        jR3 = new javax.swing.JRadioButton();
        jR2 = new javax.swing.JRadioButton();
        jR1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jRmanual = new javax.swing.JRadioButton();
        jRrandom = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jTx5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTndecimales = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTx0 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTerror = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTvalorer = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTvalorx = new javax.swing.JTextArea();
        jBlimpiar = new javax.swing.JButton();
        jBcorrer = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel1.setText("x");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(440, 50, 20, 30);

        jLabel2.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel2.setText("N° decimales");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 170, 90, 30);
        jPanel1.add(jTx);
        jTx.setBounds(400, 50, 40, 30);
        jPanel1.add(jTx6);
        jTx6.setBounds(50, 50, 40, 30);

        jLabel3.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel3.setText(",");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 130, 10, 30);
        jPanel1.add(jTx1);
        jTx1.setBounds(260, 120, 40, 30);

        jLabel4.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel4.setText("x^5");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 50, 30, 30);
        jPanel1.add(jTx4);
        jTx4.setBounds(190, 50, 40, 30);

        jLabel5.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel5.setText("x^4");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(230, 50, 30, 30);
        jPanel1.add(jTx3);
        jTx3.setBounds(260, 50, 40, 30);

        jLabel6.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel6.setText("x^3");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(300, 50, 30, 30);
        jPanel1.add(jTx2);
        jTx2.setBounds(330, 50, 40, 30);

        jLabel7.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel7.setText("x^2");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(370, 50, 30, 30);
        jPanel1.add(jTc);
        jTc.setBounds(450, 50, 40, 30);

        jRc.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jRc.setText("c");
        jRc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRcActionPerformed(evt);
            }
        });
        jPanel1.add(jRc);
        jRc.setBounds(450, 20, 50, 30);

        jR6.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jR6.setText("x^6");
        jR6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR6ActionPerformed(evt);
            }
        });
        jPanel1.add(jR6);
        jR6.setBounds(50, 20, 60, 30);

        jR5.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jR5.setText("x^5");
        jR5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR5ActionPerformed(evt);
            }
        });
        jPanel1.add(jR5);
        jR5.setBounds(120, 20, 60, 30);

        jR4.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jR4.setText("x^4");
        jR4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR4ActionPerformed(evt);
            }
        });
        jPanel1.add(jR4);
        jR4.setBounds(190, 20, 60, 30);

        jR3.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jR3.setText("x^3");
        jR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR3ActionPerformed(evt);
            }
        });
        jPanel1.add(jR3);
        jR3.setBounds(260, 20, 60, 30);

        jR2.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jR2.setText("x^2");
        jR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR2ActionPerformed(evt);
            }
        });
        jPanel1.add(jR2);
        jR2.setBounds(330, 20, 60, 30);

        jR1.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jR1.setText("x");
        jR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR1ActionPerformed(evt);
            }
        });
        jPanel1.add(jR1);
        jR1.setBounds(400, 20, 50, 30);

        jLabel8.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel8.setText("f(x)=");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 50, 50, 30);

        jRmanual.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jRmanual.setText("Manual");
        jRmanual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRmanualActionPerformed(evt);
            }
        });
        jPanel1.add(jRmanual);
        jRmanual.setBounds(410, 120, 80, 32);

        jRrandom.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jRrandom.setText("Random");
        jRrandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRrandomActionPerformed(evt);
            }
        });
        jPanel1.add(jRrandom);
        jRrandom.setBounds(20, 120, 80, 32);

        jLabel9.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel9.setText("x^6");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(90, 50, 30, 30);
        jPanel1.add(jTx5);
        jTx5.setBounds(120, 50, 40, 30);

        jLabel10.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel10.setText("]");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(300, 120, 10, 30);
        jPanel1.add(jTndecimales);
        jTndecimales.setBounds(360, 170, 130, 30);

        jLabel11.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel11.setText("[");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(200, 120, 10, 30);

        jLabel12.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel12.setText("Intervalo:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 90, 70, 30);
        jPanel1.add(jTx0);
        jTx0.setBounds(210, 120, 40, 30);

        jLabel13.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel13.setText("Er");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(380, 210, 30, 30);

        jTerror.setText("0");
        jPanel1.add(jTerror);
        jTerror.setBounds(70, 170, 130, 30);

        jLabel14.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel14.setText("Error:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 170, 50, 30);

        jLabel15.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel15.setText("X");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(110, 210, 30, 30);

        jTvalorer.setColumns(20);
        jTvalorer.setRows(5);
        jScrollPane1.setViewportView(jTvalorer);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(280, 240, 210, 270);

        jTvalorx.setColumns(20);
        jTvalorx.setRows(5);
        jScrollPane2.setViewportView(jTvalorx);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 240, 210, 270);

        jBlimpiar.setText("Limpiar");
        jBlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jBlimpiar);
        jBlimpiar.setBounds(370, 520, 120, 25);

        jBcorrer.setText("Correr");
        jBcorrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcorrerActionPerformed(evt);
            }
        });
        jPanel1.add(jBcorrer);
        jBcorrer.setBounds(20, 520, 120, 25);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final/weather-2400074_1280.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(0, 0, 520, 570);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jR6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR6ActionPerformed
        if (jR6.isSelected() == true) {
            jTx6.setEnabled(true);

        } else {
            jTx6.setEnabled(false);
        }
    }//GEN-LAST:event_jR6ActionPerformed

    private void jR5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR5ActionPerformed
        if (jR5.isSelected() == true) {
            jTx5.setEnabled(true);

        } else {
            jTx5.setEnabled(false);
        }
    }//GEN-LAST:event_jR5ActionPerformed

    private void jR4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR4ActionPerformed
        if (jR4.isSelected() == true) {
            jTx4.setEnabled(true);

        } else {
            jTx4.setEnabled(false);
        }
    }//GEN-LAST:event_jR4ActionPerformed

    private void jR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR3ActionPerformed
        if (jR3.isSelected() == true) {
            jTx3.setEnabled(true);

        } else {
            jTx3.setEnabled(false);
        }
    }//GEN-LAST:event_jR3ActionPerformed

    private void jR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR2ActionPerformed
        if (jR2.isSelected() == true) {
            jTx2.setEnabled(true);

        } else {
            jTx2.setEnabled(false);
        }
    }//GEN-LAST:event_jR2ActionPerformed

    private void jR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR1ActionPerformed
        if (jR1.isSelected() == true) {
            jTx.setEnabled(true);

        } else {
            jTx.setEnabled(false);
        }
    }//GEN-LAST:event_jR1ActionPerformed

    private void jRcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRcActionPerformed
        if (jRc.isSelected() == true) {
            jTc.setEnabled(true);

        } else {
            jTc.setEnabled(false);
        }
    }//GEN-LAST:event_jRcActionPerformed

    private void jRrandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRrandomActionPerformed
        if (jRrandom.isSelected() == true) {
            jTx0.setEnabled(false);
            jTx1.setEnabled(false);
            jRmanual.setEnabled(false);

//            x1 = (int) (Math.random() * c) + c;
//            jTx1.setText(Integer.toString((int) x1));
//            rex6 = Math.abs(x1 % 2);
//            System.out.println(x1);
        } else {
            jTx0.setEnabled(false);
            jTx1.setEnabled(false);
            jRmanual.setEnabled(true);
            jTx0.setText("0");
            jTx1.setText("0");
        }
    }//GEN-LAST:event_jRrandomActionPerformed

    private void jRmanualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRmanualActionPerformed
        if (jRmanual.isSelected() == true) {
            jRrandom.setEnabled(false);
            jTx0.setEnabled(true);
            jTx1.setEnabled(true);
        } else {
            jRrandom.setEnabled(true);
            jTx0.setEnabled(false);
            jTx1.setEnabled(false);
            jTx0.setText("0");
            jTx1.setText("0");
        }
    }//GEN-LAST:event_jRmanualActionPerformed

    private void jBlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimpiarActionPerformed
        jTc.setEnabled(false);
        jTx.setEnabled(false);
        jTx2.setEnabled(false);
        jTx3.setEnabled(false);
        jTx4.setEnabled(false);
        jTx5.setEnabled(false);
        jTx6.setEnabled(false);
        jTc.setText("");
        jTx.setText("");
        jTx2.setText("");
        jTx3.setText("");
        jTx4.setText("");
        jTx5.setText("");
        jTx6.setText("");
        jTerror.setText("");
        jTndecimales.setText("");
        jTx0.setText("");
        jTx1.setText("");
        jTvalorer.setText("");
        jTvalorx.setText("");
    }//GEN-LAST:event_jBlimpiarActionPerformed

    private void jBcorrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcorrerActionPerformed
        if (jTx6.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "x^6 se encuentra vacia");
        } else {
            try {
                x6 = Double.parseDouble(jTx6.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en la x^6");
            }
        }
        if (jTx5.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "x^5 se encuentra vacia");
        } else {
            try {
                x5 = Double.parseDouble(jTx5.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en la x^5");
            }
        }
        if (jTx4.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "x^4 se encuentra vacia");
        } else {
            try {
                x4 = Double.parseDouble(jTx4.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en la x^4");
            }
        }
        if (jTx3.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "x^3 se encuentra vacia");
        } else {
            try {
                x3 = Double.parseDouble(jTx3.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en la x^3");
            }
        }
        if (jTx2.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "x^2 se encuentra vacia");
        } else {
            try {
                x2 = Double.parseDouble(jTx2.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en la x^2");
            }
        }
        if (jTx.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "x se encuentra vacia");
        } else {
            try {
                x = Double.parseDouble(jTx.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en la x");
            }
        }
        if (jTc.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "c se encuentra vacia");
        } else {
            try {
                c = Double.parseDouble(jTc.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en la c");
            }
        }
        if (jTx0.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "El intervalo Xo se encuentra vacia");
        } else {
            try {
                x0 = Double.parseDouble(jTx0.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros en el intervalo Xo");
            }
        }
        if (jTx1.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "El intervalo X1 se encuentra vacia");
        } else {
            try {
                x1 = Double.parseDouble(jTx1.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese numeros enteros en el intervalo X1");
            }
        }
        if (jTndecimales.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "ndecimales se encuentra vacia");
        } else {
            try {
                ndecimales = Integer.parseInt(jTndecimales.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en ndecimales");
            }
        }
        if (jTerror.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "el error se encuentra vacia");
        } else {
            try {
                errorre = Double.parseDouble(jTerror.getText());//string a double
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo numeros enteros en el error");
            }
        }
        if ((jR6.isSelected() == true && jR5.isSelected() == true && jR4.isSelected() == true && jR3.isSelected() == true && jR2.isSelected() == true && jR1.isSelected() == true && jRc.isSelected() == true)) {
            rex6 = x6 * x0;
            System.out.println("x6 " + rex6);
        } else if (jR5.isSelected() == true && jR4.isSelected() == true && jR3.isSelected() == true && jR2.isSelected() == true && jR1.isSelected() == true && jRc.isSelected() == true) {
            rex5 = x5 * x0;
            System.out.println("x5 " + rex5);
        } else if (jR4.isSelected() == true && jR3.isSelected() == true && jR2.isSelected() == true && jR1.isSelected() == true && jRc.isSelected() == true) {
            if (jRmanual.isSelected() == true || jRrandom.isSelected() == false) {
                System.out.println(x4);
                rex4 = x4 * x0;
                rex4 = x3 + rex4;
                System.out.println("2 " + rex4);
                rex4 = rex4 * x0;
                rex4 = x2 + rex4;
                System.out.println("4 " + rex4);
                rex4 = rex4 * x0;
                rex4 = x + rex4;
                System.out.println("6 " + rex4);
                rex4 = rex4 * x0;
                rex4 = c + rex4;
                System.out.println("8 " + rex4);
                System.out.println(x4);
                rex44 = x4 * x1;
                rex44 = x3 + rex44;
                System.out.println("2 " + rex44);
                rex44 = rex44 * x1;
                rex44 = x2 + rex44;
                System.out.println("4 " + rex44);
                rex44 = rex44 * x1;
                rex44 = x + rex44;
                System.out.println("6 " + rex44);
                rex44 = rex44 * x1;
                rex44 = c + rex44;
                System.out.println("8 " + rex44);
                System.out.println("rex4 " + rex4 + " rex44 " + rex44);
            }
            if (jRmanual.isSelected() == false || jRrandom.isSelected() == true) {
                System.out.println("Random");

                do {
                    System.out.println(c);
                    int x0 = (int) (Math.random() * c);
                    jTx0.setText(Integer.toString((int) x0));
                    rex = Math.abs(x0 % 2);
                    System.out.println("x0 " + x0);
                    System.out.println(c);
                    int x1 = (int) (Math.random() * c);
                    jTx1.setText(Integer.toString((int) x1));
                    rex = Math.abs(x1 % 2);
                    System.out.println("xq " + x1);
                } while (x0 % 2 != 0 || x1 % 2 != 0);
                System.out.println("Si soy divisible " + x0 + "\nsoy divisible " + x1);
            }
        } else if ((jR3.isSelected() == true && jR2.isSelected() == true && jR1.isSelected() == true && jRc.isSelected() == true)||
                (jR3.isSelected() == true && jR2.isSelected() == false && jR1.isSelected() == true && jRc.isSelected() == true)||
                (jR3.isSelected() == true && jR2.isSelected() == false && jR1.isSelected() == false && jRc.isSelected() == true)||
                (jR3.isSelected() == true && jR2.isSelected() == false && jR1.isSelected() == false && jRc.isSelected() == false)||
                (jR3.isSelected() == true && jR2.isSelected() == true && jR1.isSelected() == false && jRc.isSelected() == false)||
                (jR3.isSelected() == true && jR2.isSelected() == true && jR1.isSelected() == false && jRc.isSelected() == false)||
                 (jR3.isSelected() == true && jR2.isSelected() == true && jR1.isSelected() == false && jRc.isSelected() == true)) {
            if (jRmanual.isSelected() == true || jRrandom.isSelected() == false) {
                System.out.println(x3);
                rex4 = x3 * x0;
                rex4 = x2 + rex4;
                System.out.println("2 " + rex4);
                rex4 = rex4 * x0;
                rex4 = x + rex4;
                System.out.println("4 " + rex4);
                rex4 = rex4 * x0;
                rex4 = c + rex4;
                System.out.println("6 " + rex4);
                System.out.println(x3);
                rex44 = x3 * x1;
                rex44 = x2 + rex44;
                System.out.println("2 " + rex44);
                rex44 = rex44 * x1;
                rex44 = x + rex44;
                System.out.println("4 " + rex44);
                rex44 = rex44 * x1;
                rex44 = c + rex44;
                System.out.println("6 " + rex44);
                System.out.println("rex4 " + rex4 + " rex44 " + rex44);
            }
            if (jRmanual.isSelected() == false || jRrandom.isSelected() == true) {

            }
        } else if ((jR2.isSelected() == true && jR1.isSelected() == true && jRc.isSelected() == true)
                || (jR2.isSelected() == true && jR1.isSelected() == false && jRc.isSelected() == true)
                || (jR2.isSelected() == true && jR1.isSelected() == true && jRc.isSelected() == false)
                || (jR2.isSelected() == true && jR1.isSelected() == false && jRc.isSelected() == false)) {
            if (jRmanual.isSelected() == true || jRrandom.isSelected() == false) {
                System.out.println(x2);
                rex4 = x2 * x0;
                rex4 = x + rex4;
                System.out.println("2 " + rex4);
                rex4 = rex4 * x0;
                rex4 = c + rex4;
                System.out.println("4 " + rex4);
                System.out.println(x3);
                rex44 = x2 * x1;
                rex44 = x + rex44;
                System.out.println("2 " + rex44);
                rex44 = rex44 * x1;
                rex44 = c + rex44;
                System.out.println("4 " + rex44);
                System.out.println("rex4 " + rex4 + " rex44 " + rex44);
            }
            if (jRmanual.isSelected() == false || jRrandom.isSelected() == true) {

            }

        } else if ((jR1.isSelected() == true && jRc.isSelected() == true) ||
                (jR1.isSelected() == true && jRc.isSelected() == false)) {
            System.out.println(x);
            rex4 = x * x0;
            rex4 = c + rex4;
            System.out.println("2 " + rex4);
            System.out.println(x3);
            rex44 = x * x1;
            rex44 = c + rex44;
            System.out.println("2 " + rex44);
            System.out.println("rex4 " + rex4 + " rex44 " + rex44);

        } else if (jRc.isSelected() == true) {
            rec = c * x0;
            System.out.println("c " + rec);
        }

        if ((rex4 > 0 && rex44 > 0) || (rex4 < 0 && rex44 < 0)) {/////////////////////////////////////validar si tienen signos iguales
            JOptionPane.showMessageDialog(null, "No hay solucion favor de poner otro\nintervalo ya sea manual o random");
        } else {
            System.out.println(rex4);
            rex4 = (x0 + x1) / 2;
            System.out.println("re " + rex4);
            rex44 = 0;
            System.out.println(rex44);
            if (jR6.isSelected() == true && jR5.isSelected() == true && jR4.isSelected() == true && jR3.isSelected() == true && jR2.isSelected() == true && jR1.isSelected() == true && jRc.isSelected() == true) {
                rex6 = x6 * x0;
                System.out.println("x6 " + rex6);
            } else if (jR5.isSelected() == true && jR4.isSelected() == true && jR3.isSelected() == true && jR2.isSelected() == true && jR1.isSelected() == true && jRc.isSelected() == true) {
                rex5 = x5 * x0;
                System.out.println("x5 " + rex5);
            } else if (jR4.isSelected() == true && jR3.isSelected() == true && jR2.isSelected() == true && jR1.isSelected() == true && jRc.isSelected() == true) {
                if (jRmanual.isSelected() == true || jRrandom.isSelected() == false) {
                    jTvalorx.append("X 0= " + rex4 + "\n");
                    do {
                        rex2 = x4 * rex4;//1
                        rex2 = x3 + rex2;//1
                        rex44 = x4 * rex4;
                        rex44 = rex44 + rex2;
                        rex2 = rex2 * rex4;//1
                        rex2 = x2 + rex2;//1
                        rex44 = rex44 * rex4;//2
                        rex44 = rex44 + rex2;//2
                        rex2 = rex2 * rex4;//1
                        rex2 = x + rex2;//1
                        rex44 = rex44 * rex4;//2
                        rex44 = rex44 + rex2;//2
                        rex2 = rex2 * rex4;//1
                        rex2 = c + rex2;//1
                        System.out.println("rex4 " + rex2 + " rex44 " + rex44);
                        xi = rex4 - rex2 / rex44;
                        System.out.println(xi);
                        er = Math.abs(((xi - rex4) / xi) * 100);
                        System.out.println(er);
                        rex4 = xi;
                        System.out.println("soy nuevo " + rex4);
                        BigDecimal x = new BigDecimal(rex4);
                        x = x.setScale(ndecimales, RoundingMode.HALF_UP);
                        BigDecimal e = new BigDecimal(er);
                        e = e.setScale(ndecimales, RoundingMode.HALF_UP);
                        rexx = x.doubleValue();
                        recc = e.doubleValue();
                        jTvalorx.append("X " + conta + "= " + rexx + "\n");
                        jTvalorer.append("X " + conta + "= " + recc + "%\n");
                        conta++;

                    } while (er >= errorre);
                }
                if (jRmanual.isSelected() == false || jRrandom.isSelected() == true) {

                }
            } else if ((jR3.isSelected() == true && jR2.isSelected() == true && jR1.isSelected() == true && jRc.isSelected() == true)||
                (jR3.isSelected() == true && jR2.isSelected() == false && jR1.isSelected() == true && jRc.isSelected() == true)||
                (jR3.isSelected() == true && jR2.isSelected() == false && jR1.isSelected() == false && jRc.isSelected() == true)||
                (jR3.isSelected() == true && jR2.isSelected() == false && jR1.isSelected() == false && jRc.isSelected() == false)||
                (jR3.isSelected() == true && jR2.isSelected() == true && jR1.isSelected() == false && jRc.isSelected() == false)||
                (jR3.isSelected() == true && jR2.isSelected() == true && jR1.isSelected() == false && jRc.isSelected() == false)||
                 (jR3.isSelected() == true && jR2.isSelected() == true && jR1.isSelected() == false && jRc.isSelected() == true)) {
                if (jRmanual.isSelected() == true || jRrandom.isSelected() == false) {
                    jTvalorx.append("X 0= " + rex4 + "\n");
                    do {
                        rex2 = x3 * rex4;//1
                        rex2 = x2 + rex2;//1
                        System.out.println("1 " + rex2);
                        rex44 = x3 * rex4;//2
                        rex44 = rex44 + rex2;//2
                        System.out.println("2 " + rex44);
                        rex2 = rex2 * rex4;//1
                        rex2 = x + rex2;//1
                        System.out.println("1 " + rex2);
                        rex44 = rex44 * rex4;//2
                        rex44 = rex44 + rex2;//2
                        System.out.println("2 " + rex44);
                        rex2 = rex2 * rex4;//1
                        rex2 = c + rex2;//1
                        System.out.println("1 " + rex2);
                        rex44 = rex44 * rex4;//2
                        rex44 = rex44 + rex2;//2
                        System.out.println("2 " + rex44);
                        System.out.println("rex4 " + rex2 + " rex44 " + rex44);
                        xi = rex4 - rex2 / rex44;
                        System.out.println(xi);
                        er = Math.abs(((xi - rex4) / xi) * 100);
                        System.out.println(er);
                        rex4 = xi;
                        System.out.println("soy nuevo " + rex4);
                        BigDecimal x = new BigDecimal(rex4);
                        x = x.setScale(ndecimales, RoundingMode.HALF_UP);
                        BigDecimal e = new BigDecimal(er);
                        e = e.setScale(ndecimales, RoundingMode.HALF_UP);
                        rexx = x.doubleValue();
                        recc = e.doubleValue();
                        jTvalorx.append("X " + conta + "= " + rexx + "\n");
                        jTvalorer.append("X " + conta + "= " + recc + "%\n");
                        conta++;

                    } while (er >= errorre);
                }
                if (jRmanual.isSelected() == false || jRrandom.isSelected() == true) {

                }

            } else if ((jR2.isSelected() == true && jR1.isSelected() == true && jRc.isSelected() == true)
                    || (jR2.isSelected() == true && jR1.isSelected() == false && jRc.isSelected() == true)
                    || (jR2.isSelected() == true && jR1.isSelected() == true && jRc.isSelected() == false)
                    || (jR2.isSelected() == true && jR1.isSelected() == false && jRc.isSelected() == false)) {
                if (jRmanual.isSelected() == true || jRrandom.isSelected() == false) {
                    jTvalorx.append("X 0= " + rex4 + "\n");
                    do {
                        rex2 = x2 * rex4;//1
                        rex2 = x + rex2;//1
                        System.out.println("1 " + rex2);
                        rex44 = x2 * rex4;//2
                        rex44 = rex44 + rex2;//2
                        System.out.println("2 " + rex44);
                        rex2 = rex2 * rex4;//1
                        rex2 = c + rex2;//1
                        System.out.println("1 " + rex2);
                        rex44 = rex44 * rex4;//2
                        rex44 = rex44 + rex2;//2
                        System.out.println("rex4 " + rex2 + " rex44 " + rex44);
                        xi = rex4 - rex2 / rex44;
                        System.out.println(xi);
                        er = Math.abs(((xi - rex4) / xi) * 100);
                        System.out.println(er);
                        rex4 = xi;
                        System.out.println("soy nuevo " + rex4);
                        BigDecimal x = new BigDecimal(rex4);
                        x = x.setScale(ndecimales, RoundingMode.HALF_UP);
                        BigDecimal e = new BigDecimal(er);
                        e = e.setScale(ndecimales, RoundingMode.HALF_UP);
                        rexx = x.doubleValue();
                        recc = e.doubleValue();
                        jTvalorx.append("X " + conta + "= " + rexx + "\n");
                        jTvalorer.append("X " + conta + "= " + recc + "%\n");
                        conta++;

                    } while (er >= errorre || conta < 30);
                }
                if (jRmanual.isSelected() == false || jRrandom.isSelected() == true) {

                }

            } else if ((jR1.isSelected() == true && jRc.isSelected() == true)||
                    (jR1.isSelected() == true && jRc.isSelected() == false)){
                if (jRmanual.isSelected() == true || jRrandom.isSelected() == false) {
                    jTvalorx.append("X 0= " + rex4 + "\n");
                    do {
                        rex2 = x * rex4;//1
                        rex2 = c + rex2;//1
                        System.out.println("1 " + rex2);
                        rex44 = x * rex4;//2
                        rex44 = rex44 + rex2;//2
                        System.out.println("2 " + rex44);
                        System.out.println("rex4 " + rex2 + " rex44 " + rex44);
                        xi = rex4 - rex2 / rex44;
                        System.out.println(xi);
                        er = Math.abs(((xi - rex4) / xi) * 100);
                        System.out.println(er);
                        rex4 = xi;
                        System.out.println("soy nuevo " + rex4);
                        BigDecimal x = new BigDecimal(rex4);
                        x = x.setScale(ndecimales, RoundingMode.HALF_UP);
                        BigDecimal e = new BigDecimal(er);
                        e = e.setScale(ndecimales, RoundingMode.HALF_UP);
                        rexx = x.doubleValue();
                        recc = e.doubleValue();
                        jTvalorx.append("X " + conta + "= " + rexx + "\n");
                        jTvalorer.append("X " + conta + "= " + recc + "%\n");
                        conta++;

                    } while (er >= errorre);
                }
                if (jRmanual.isSelected() == false || jRrandom.isSelected() == true) {

                }

            } else if (jRc.isSelected() == true) {
                rec = c * x0;
                System.out.println("c " + rec);
            }
        }

//        if (jR1.isSelected() == true || jR2.isSelected() == true || jR3.isSelected() == true || jR4.isSelected() == true || jR5.isSelected() == true || jR6.isSelected() == true || jRc.isSelected() == true) {
//            if (jRmanual.isSelected() == true) {
//                System.out.println(Arrays.toString(arreglo));
//                arresx1[7]=x0*arreglo.length;
//                       System.out.println(arresx1[7]);
//            }
//        }

    }//GEN-LAST:event_jBcorrerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Metodoresiduos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Metodoresiduos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Metodoresiduos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Metodoresiduos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Metodoresiduos popo = new Metodoresiduos();
                popo.setVisible(true);
                popo.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcorrer;
    private javax.swing.JButton jBlimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jR1;
    private javax.swing.JRadioButton jR2;
    private javax.swing.JRadioButton jR3;
    private javax.swing.JRadioButton jR4;
    private javax.swing.JRadioButton jR5;
    private javax.swing.JRadioButton jR6;
    private javax.swing.JRadioButton jRc;
    private javax.swing.JRadioButton jRmanual;
    private javax.swing.JRadioButton jRrandom;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTc;
    private javax.swing.JTextField jTerror;
    private javax.swing.JTextField jTndecimales;
    private javax.swing.JTextArea jTvalorer;
    private javax.swing.JTextArea jTvalorx;
    private javax.swing.JTextField jTx;
    private javax.swing.JTextField jTx0;
    private javax.swing.JTextField jTx1;
    private javax.swing.JTextField jTx2;
    private javax.swing.JTextField jTx3;
    private javax.swing.JTextField jTx4;
    private javax.swing.JTextField jTx5;
    private javax.swing.JTextField jTx6;
    // End of variables declaration//GEN-END:variables
}
